import { RegulationSeed } from "./types";

export const CIS_CONTROLS_V8_SEED: RegulationSeed = {
  code: "CIS_V8",
  name: "CIS Critical Security Controls v8",
  type: "framework",
  category: "information_security",
  jurisdiction: "Global",
  issuer: "CIS",
  version: "v8",
  description:
    "A prioritized set of actions to protect organizations and data from known cyber attack vectors, organized into 18 Implementation Groups.",
  effectiveDate: "2021-05-18",
  requirements: [
    {
      code: "IG1",
      title: "Inventory and Control of Enterprise Assets",
      level: 0, orderNo: 1,
      children: [
        { code: "1.1", title: "Establish and maintain detailed enterprise asset inventory", level: 1, orderNo: 1, description: "Establish and maintain an accurate, detailed, and up-to-date inventory of all enterprise assets with the potential to store or process data." },
        { code: "1.2", title: "Address unauthorized assets", level: 1, orderNo: 2, description: "Ensure processes are in place to address unauthorized assets on a weekly basis and remove or remediate them." },
        { code: "1.3", title: "Use approved hardware and software", level: 1, orderNo: 3, description: "Use only actively supported, assigned, and approved hardware and software components in the enterprise asset inventory." },
        { code: "1.4", title: "Maintain asset lifecycle management", level: 1, orderNo: 4, description: "Manage enterprise assets throughout their lifecycle including procurement, deployment, maintenance, and secure disposal." },
      ],
    },
    {
      code: "IG2",
      title: "Inventory and Control of Software Assets",
      level: 0, orderNo: 2,
      children: [
        { code: "2.1", title: "Establish and maintain software inventory", level: 1, orderNo: 1, description: "Establish and maintain a detailed software inventory covering all software installed on enterprise assets." },
        { code: "2.2", title: "Ensure authorized software only", level: 1, orderNo: 2, description: "Ensure that only currently approved software is installed or executed on enterprise assets through application allowlisting." },
        { code: "2.3", title: "Address unauthorized software", level: 1, orderNo: 3, description: "Ensure unauthorized software is removed from enterprise assets or inventoried in a timely manner." },
        { code: "2.4", title: "Use automated software inventory tools", level: 1, orderNo: 4, description: "Deploy automated tools to maintain software inventory and detect unauthorized or unapproved software installations." },
        { code: "2.5", title: "Manage software vulnerabilities", level: 1, orderNo: 5, description: "Track, review, and remediate software vulnerabilities identified in the software inventory according to prioritization." },
        { code: "2.6", title: "Maintain software licenses", level: 1, orderNo: 6, description: "Track software license usage and ensure compliance with licensing terms to avoid legal and security risks." },
      ],
    },
    {
      code: "IG3",
      title: "Data Protection",
      level: 0, orderNo: 3,
      children: [
        { code: "3.1", title: "Establish and maintain data management process", level: 1, orderNo: 1, description: "Establish and maintain a data management process covering data classification, handling, storage, retention, and disposal." },
        { code: "3.2", title: "Establish and maintain an inventory of data", level: 1, orderNo: 2, description: "Establish and maintain an inventory of sensitive data including data location, classification, and ownership." },
        { code: "3.3", title: "Configure data access controls", level: 1, orderNo: 3, description: "Configure data access controls according to the principle of least privilege and data classification requirements." },
        { code: "3.4", title: "Encrypt data at rest", level: 1, orderNo: 4, description: "Encrypt sensitive data at rest on servers, workstations, mobile devices, and removable media." },
        { code: "3.5", title: "Encrypt data in transit", level: 1, orderNo: 5, description: "Encrypt sensitive data in transit using TLS or equivalent secure protocols for all network communications." },
        { code: "3.6", title: "Automate data backups", level: 1, orderNo: 6, description: "Automate backups of sensitive data and maintain at least three copies on different media types." },
        { code: "3.7", title: "Establish data retention and disposal procedures", level: 1, orderNo: 7, description: "Establish and maintain data retention schedules and secure disposal procedures for all sensitive data." },
        { code: "3.8", title: "Log data access and modifications", level: 1, orderNo: 8, description: "Log and monitor access to and modifications of sensitive data with automated alerts for anomalous activity." },
      ],
    },
    {
      code: "IG4",
      title: "Secure Configuration of Enterprise Assets and Software",
      level: 0, orderNo: 4,
      children: [
        { code: "4.1", title: "Establish secure configuration processes", level: 1, orderNo: 1, description: "Establish and maintain secure configuration processes for enterprise assets and software following industry benchmarks." },
        { code: "4.2", title: "Reimage devices with secure configuration", level: 1, orderNo: 2, description: "Reimage or apply baseline secure configurations to all enterprise assets before deployment or after maintenance." },
        { code: "4.3", title: "Manage default accounts and passwords", level: 1, orderNo: 3, description: "Change default passwords and disable or rename default accounts on all enterprise assets before deployment." },
        { code: "4.4", title: "Uninstall and disable unnecessary services", level: 1, orderNo: 4, description: "Uninstall or disable unnecessary services, protocols, daemons, and functionality on all enterprise assets." },
        { code: "4.5", title: "Use automated configuration monitoring tools", level: 1, orderNo: 5, description: "Deploy automated tools to continuously monitor and remediate configuration drift from baseline standards." },
        { code: "4.6", title: "Apply secure configuration to cloud environments", level: 1, orderNo: 6, description: "Apply CIS benchmarks or equivalent secure configurations to cloud infrastructure including IaaS, PaaS, and SaaS." },
      ],
    },
    {
      code: "IG5",
      title: "Account Management",
      level: 0, orderNo: 5,
      children: [
        { code: "5.1", title: "Establish and maintain identity inventory", level: 1, orderNo: 1, description: "Establish and maintain an inventory of all accounts managed through identity and access management systems." },
        { code: "5.2", title: "Use unique credentials for all accounts", level: 1, orderNo: 2, description: "Assign unique credentials to each user account and ensure no shared or group accounts for critical systems." },
        { code: "5.3", title: "Disable dormant accounts", level: 1, orderNo: 3, description: "Disable accounts that have been inactive for 45 days or more and remove orphaned accounts promptly." },
        { code: "5.4", title: "Restrict administrator privileges", level: 1, orderNo: 4, description: "Restrict administrator privileges to dedicated administrator accounts and require separate accounts for non-administrative activities." },
        { code: "5.5", title: "Manage service and application accounts", level: 1, orderNo: 5, description: "Manage service accounts and application accounts securely including password rotation and least privilege." },
        { code: "5.6", title: "Implement privileged access management", level: 1, orderNo: 6, description: "Implement privileged access management solutions including just-in-time access and session recording for privileged accounts." },
      ],
    },
    {
      code: "IG6",
      title: "Access Control Management",
      level: 0, orderNo: 6,
      children: [
        { code: "6.1", title: "Establish access control policy", level: 1, orderNo: 1, description: "Establish and maintain an access control policy based on the principle of least privilege and need-to-know." },
        { code: "6.2", title: "Enforce MFA for administrative access", level: 1, orderNo: 2, description: "Require multi-factor authentication for all administrative access to enterprise assets, both on-premises and remote." },
        { code: "6.3", title: "Enforce MFA for remote access", level: 1, orderNo: 3, description: "Require multi-factor authentication for all remote network access to enterprise assets from outside the corporate network." },
        { code: "6.4", title: "Review and recertify access rights", level: 1, orderNo: 4, description: "Review and recertify user and group access rights at least quarterly and remove inappropriate or excessive permissions." },
        { code: "6.5", title: "Centralize access control", level: 1, orderNo: 5, description: "Centralize access control through directory services, SSO, and identity federation wherever feasible." },
        { code: "6.6", title: "Log and monitor access control changes", level: 1, orderNo: 6, description: "Log and monitor all access control changes and generate alerts for unauthorized or suspicious modifications." },
      ],
    },
    {
      code: "IG7",
      title: "Continuous Vulnerability Management",
      level: 0, orderNo: 7,
      children: [
        { code: "7.1", title: "Establish vulnerability management process", level: 1, orderNo: 1, description: "Establish and maintain a vulnerability management process covering vulnerability scanning, prioritization, and remediation." },
        { code: "7.2", title: "Conduct automated vulnerability scans", level: 1, orderNo: 2, description: "Conduct automated vulnerability scans of enterprise assets on a continuous basis using up-to-date vulnerability databases." },
        { code: "7.3", title: "Prioritize vulnerability remediation", level: 1, orderNo: 3, description: "Prioritize vulnerability remediation based on exploitability, asset criticality, and threat intelligence." },
        { code: "7.4", title: "Remediate vulnerabilities within SLA", level: 1, orderNo: 4, description: "Remediate critical vulnerabilities within 7 days, high vulnerabilities within 15 days, and medium vulnerabilities within 30 days." },
        { code: "7.5", title: "Conduct container and orchestration scanning", level: 1, orderNo: 5, description: "Conduct vulnerability scanning of container images and orchestration configurations in development and production." },
      ],
    },
    {
      code: "IG8",
      title: "Audit Log Management",
      level: 0, orderNo: 8,
      children: [
        { code: "8.1", title: "Establish audit logging processes", level: 1, orderNo: 1, description: "Establish and maintain an audit logging process covering log sources, retention, protection, and review." },
        { code: "8.2", title: "Collect authentication logs", level: 1, orderNo: 2, description: "Collect authentication and authorization logs from all enterprise assets including successful and failed attempts." },
        { code: "8.3", title: "Enable detailed logging", level: 1, orderNo: 3, description: "Enable detailed logging on enterprise assets covering security events, administrative actions, and system changes." },
        { code: "8.4", title: "Standardize log formats", level: 1, orderNo: 4, description: "Standardize and centralize log collection using syslog, CEF, or equivalent standardized logging formats." },
        { code: "8.5", title: "Collect DNS and network logs", level: 1, orderNo: 5, description: "Collect DNS query logs, network flow logs, and proxy logs to support threat detection and investigation." },
        { code: "8.6", title: "Retain logs for at least 90 days", level: 1, orderNo: 6, description: "Retain audit logs for at least 90 days and make them available for analysis. Archive logs for at least 12 months." },
      ],
    },
    {
      code: "IG9",
      title: "Email and Web Browser Protections",
      level: 0, orderNo: 9,
      children: [
        { code: "9.1", title: "Implement email security controls", level: 1, orderNo: 1, description: "Implement DMARC, DKIM, and SPF email authentication to protect against email spoofing and phishing." },
        { code: "9.2", title: "Block malicious attachments and links", level: 1, orderNo: 2, description: "Deploy email security gateways to detect and block malicious attachments, URLs, and phishing attempts." },
        { code: "9.3", title: "Enforce web browser security", level: 1, orderNo: 3, description: "Configure web browsers to block dangerous content including pop-ups, automatic downloads, and insecure plugins." },
        { code: "9.4", title: "Implement URL filtering", level: 1, orderNo: 4, description: "Deploy web proxy or DNS filtering to block access to known malicious, phishing, and unauthorized categories of websites." },
        { code: "9.5", title: "Use browser isolation for high-risk browsing", level: 1, orderNo: 5, description: "Use remote browser isolation or sandboxing for high-risk browsing activities to prevent malware from reaching endpoints." },
      ],
    },
    {
      code: "IG10",
      title: "Malware Defenses",
      level: 0, orderNo: 10,
      children: [
        { code: "10.1", title: "Deploy anti-malware software", level: 1, orderNo: 1, description: "Deploy and maintain anti-malware software on all enterprise assets including endpoint detection and response capabilities." },
        { code: "10.2", title: "Configure automatic malware scanning", level: 1, orderNo: 2, description: "Configure anti-malware software to perform automatic scans of files, email attachments, and removable media." },
        { code: "10.3", title: "Enable behavior-based detection", level: 1, orderNo: 3, description: "Enable behavior-based and heuristic detection in anti-malware solutions to detect zero-day and fileless malware." },
        { code: "10.4", title: "Disable autorun and autoplay", level: 1, orderNo: 4, description: "Disable autorun and autoplay for all removable media to prevent malware propagation via USB drives." },
        { code: "10.5", title: "Implement endpoint detection and response", level: 1, orderNo: 5, description: "Deploy EDR solutions on enterprise assets to continuously monitor and respond to advanced threats." },
      ],
    },
    {
      code: "IG11",
      title: "Data Recovery",
      level: 0, orderNo: 11,
      children: [
        { code: "11.1", title: "Establish data recovery procedures", level: 1, orderNo: 1, description: "Establish and maintain data recovery procedures including backup schedules, retention periods, and recovery testing." },
        { code: "11.2", title: "Automate backups", level: 1, orderNo: 2, description: "Automate backups of critical data and systems and protect backups from unauthorized access and ransomware." },
        { code: "11.3", title: "Test data recovery", level: 1, orderNo: 3, description: "Test data recovery procedures at least annually to validate that data can be restored within required recovery objectives." },
        { code: "11.4", title: "Maintain separate backup infrastructure", level: 1, orderNo: 4, description: "Maintain backups on separate infrastructure with air-gapped or immutable storage to protect against ransomware." },
        { code: "11.5", title: "Protect backup data", level: 1, orderNo: 5, description: "Encrypt backup data both at rest and in transit and implement strong access controls for backup systems." },
      ],
    },
    {
      code: "IG12",
      title: "Network Infrastructure Management",
      level: 0, orderNo: 12,
      children: [
        { code: "12.1", title: "Maintain network architecture diagrams", level: 1, orderNo: 1, description: "Maintain current network architecture diagrams showing topology, segmentation, and traffic flows." },
        { code: "12.2", title: "Segment and isolate networks", level: 1, orderNo: 2, description: "Segment enterprise networks based on sensitivity and criticality using VLANs, firewalls, and network ACLs." },
        { code: "12.3", title: "Manage network device configurations", level: 1, orderNo: 3, description: "Use secure configurations for all network devices including routers, switches, firewalls, and wireless access points." },
        { code: "12.4", title: "Monitor network devices", level: 1, orderNo: 4, description: "Monitor network devices for security events, configuration changes, and performance anomalies." },
        { code: "12.5", title: "Filter network traffic", level: 1, orderNo: 5, description: "Filter network traffic between zones based on least privilege using firewall rules, ACLs, and network policies." },
      ],
    },
    {
      code: "IG13",
      title: "Network Monitoring and Defense",
      level: 0, orderNo: 13,
      children: [
        { code: "13.1", title: "Deploy network intrusion detection", level: 1, orderNo: 1, description: "Deploy network-based intrusion detection and prevention systems to monitor network traffic for malicious activity." },
        { code: "13.2", title: "Monitor network traffic for anomalies", level: 1, orderNo: 2, description: "Monitor network traffic for anomalous outbound communications, data exfiltration attempts, and command and control traffic." },
        { code: "13.3", title: "Deploy network traffic analysis tools", level: 1, orderNo: 3, description: "Deploy network traffic analysis and netflow monitoring solutions to baseline and detect anomalies." },
        { code: "13.4", title: "Monitor encrypted traffic", level: 1, orderNo: 4, description: "Monitor encrypted traffic for threats using TLS inspection or encrypted traffic analysis techniques." },
        { code: "13.5", title: "Maintain network security monitoring tools", level: 1, orderNo: 5, description: "Maintain and update network security monitoring tools including rule sets, signatures, and detection models." },
      ],
    },
    {
      code: "IG14",
      title: "Security Awareness and Skills Training",
      level: 0, orderNo: 14,
      children: [
        { code: "14.1", title: "Establish security awareness program", level: 1, orderNo: 1, description: "Establish and maintain a security awareness program to educate personnel on cybersecurity risks and best practices." },
        { code: "14.2", title: "Train on phishing awareness", level: 1, orderNo: 2, description: "Train personnel on recognizing and reporting phishing attempts including simulated phishing exercises." },
        { code: "14.3", title: "Train on data handling", level: 1, orderNo: 3, description: "Train personnel on secure data handling practices for sensitive and regulated data in all formats." },
        { code: "14.4", title: "Train on incident reporting", level: 1, orderNo: 4, description: "Train personnel on incident recognition, escalation procedures, and reporting obligations." },
        { code: "14.5", title: "Provide role-specific security training", level: 1, orderNo: 5, description: "Provide role-specific security training for personnel with unique security responsibilities." },
        { code: "14.6", title: "Track and measure training effectiveness", level: 1, orderNo: 6, description: "Track security awareness training completion and measure effectiveness through phishing simulation results and knowledge assessments." },
      ],
    },
    {
      code: "IG15",
      title: "Service Provider Management",
      level: 0, orderNo: 15,
      children: [
        { code: "15.1", title: "Establish service provider management process", level: 1, orderNo: 1, description: "Establish and maintain a service provider management process covering security requirements, contracts, and oversight." },
        { code: "15.2", title: "Assess service provider security", level: 1, orderNo: 2, description: "Assess the security posture of service providers before engagement and periodically throughout the relationship." },
        { code: "15.3", title: "Include security in service provider contracts", level: 1, orderNo: 3, description: "Include security requirements and obligations in service provider contracts and service level agreements." },
        { code: "15.4", title: "Monitor service provider compliance", level: 1, orderNo: 4, description: "Monitor service provider compliance with contractual security requirements and investigate reported incidents." },
        { code: "15.5", title: "Manage service provider access", level: 1, orderNo: 5, description: "Manage and terminate service provider access to enterprise assets promptly when services are modified or terminated." },
      ],
    },
    {
      code: "IG16",
      title: "Application Software Security",
      level: 0, orderNo: 16,
      children: [
        { code: "16.1", title: "Establish secure software development lifecycle", level: 1, orderNo: 1, description: "Establish and maintain a secure software development lifecycle integrating security into requirements, design, development, and testing." },
        { code: "16.2", title: "Conduct application security testing", level: 1, orderNo: 2, description: "Conduct SAST, DAST, and SCA testing on all internally developed and third-party application code before deployment." },
        { code: "16.3", title: "Manage open source vulnerabilities", level: 1, orderNo: 3, description: "Inventory and manage open source software components and remediate identified vulnerabilities in a timely manner." },
        { code: "16.4", title: "Secure third-party software configurations", level: 1, orderNo: 4, description: "Apply security configurations to third-party application software following industry benchmarks and vendor guidance." },
        { code: "16.5", title: "Implement API security controls", level: 1, orderNo: 5, description: "Implement authentication, authorization, rate limiting, and input validation for all application programming interfaces." },
        { code: "16.6", title: "Manage secrets in code", level: 1, orderNo: 6, description: "Scan source code repositories for embedded secrets such as passwords, tokens, and API keys, and remediate findings." },
      ],
    },
    {
      code: "IG17",
      title: "Incident Response Management",
      level: 0, orderNo: 17,
      children: [
        { code: "17.1", title: "Establish incident response plan", level: 1, orderNo: 1, description: "Establish and maintain an incident response plan with defined roles, procedures, and communication protocols." },
        { code: "17.2", title: "Assign incident response roles", level: 1, orderNo: 2, description: "Assign incident response roles and responsibilities to personnel and ensure backup coverage." },
        { code: "17.3", title: "Establish incident reporting procedures", level: 1, orderNo: 3, description: "Establish and communicate incident reporting procedures for all personnel and external parties." },
        { code: "17.4", title: "Test incident response plan", level: 1, orderNo: 4, description: "Test incident response plan at least annually using tabletop exercises, simulations, and full functional tests." },
        { code: "17.5", title: "Conduct post-incident reviews", level: 1, orderNo: 5, description: "Conduct post-incident reviews to identify lessons learned and implement improvements to incident response processes." },
        { code: "17.6", title: "Integrate threat intelligence", level: 1, orderNo: 6, description: "Integrate threat intelligence feeds into incident response processes to enhance detection and response capabilities." },
      ],
    },
    {
      code: "IG18",
      title: "Penetration Testing",
      level: 0, orderNo: 18,
      children: [
        { code: "18.1", title: "Establish penetration testing program", level: 1, orderNo: 1, description: "Establish and maintain a penetration testing program covering internal, external, and application test methodologies." },
        { code: "18.2", title: "Conduct regular penetration tests", level: 1, orderNo: 2, description: "Conduct penetration testing at least annually and after significant infrastructure or application changes." },
        { code: "18.3", title: "Remediate penetration test findings", level: 1, orderNo: 3, description: "Remediate penetration test findings based on risk priority and validate remediation through re-testing." },
        { code: "18.4", title: "Use qualified penetration testers", level: 1, orderNo: 4, description: "Use qualified and independent penetration testers with recognized certifications and proven experience." },
        { code: "18.5", title: "Define penetration test scope", level: 1, orderNo: 5, description: "Define clear penetration testing scope including in-scope systems, testing methods, rules of engagement, and exclusions." },
      ],
    },
  ],
};
