import { RegulationSeed } from "./types";

export const CMMC_2_SEED: RegulationSeed = {
  code: "CMMC_2",
  name: "Cybersecurity Maturity Model Certification 2.0",
  type: "standard",
  category: "information_security",
  jurisdiction: "US",
  issuer: "U.S. Department of Defense",
  version: "2.0",
  description:
    "CMMC 2.0 is the U.S. Department of Defense's cybersecurity certification program designed to ensure that contractors and subcontractors in the Defense Industrial Base (DIB) implement adequate cybersecurity practices to protect Federal Contract Information (FCI) and Controlled Unclassified Information (CUI). It consolidates previous maturity levels into three levels: Foundational (Level 1), Advanced (Level 2), and Expert (Level 3).",
  effectiveDate: "2025-01-01",
  requirements: [
    {
      code: "L1",
      title: "Level 1 — Foundational (Basic Safeguarding of FCI)",
      level: 0, orderNo: 1,
      children: [
        { code: "L1.1", title: "Limit information system access", level: 1, orderNo: 1, description: "Limit information system access to authorized users, processes acting on behalf of authorized users, and devices." },
        { code: "L1.2", title: "Control information system access", level: 1, orderNo: 2, description: "Limit information system access to the types of transactions and functions that authorized users are permitted to execute." },
        { code: "L1.3", title: "Screen and monitor connections", level: 1, orderNo: 3, description: "Verify and control/limit connections to and use of external information systems." },
        { code: "L1.4", title: "Control public information", level: 1, orderNo: 4, description: "Control information posted or processed on publicly accessible information systems." },
        { code: "L1.5", title: "Identify information system users", level: 1, orderNo: 5, description: "Identify information system users, processes acting on behalf of users, or devices." },
        { code: "L1.6", title: "Authenticate system users", level: 1, orderNo: 6, description: "Authenticate (or verify) the identities of those users, processes, or devices as a prerequisite to allowing access to organizational information systems." },
        { code: "L1.7", title: "Sanitize media before disposal", level: 1, orderNo: 7, description: "Sanitize or destroy information system media containing Federal Contract Information before disposal or release for reuse." },
        { code: "L1.8", title: "Escalate incidents promptly", level: 1, orderNo: 8, description: "Escalate unusual or suspicious activity to designated organizational personnel in a timely manner." },
        { code: "L1.9", title: "Update malicious code protection", level: 1, orderNo: 9, description: "Implement and regularly update malicious code protection mechanisms." },
        { code: "L1.10", title: "Update virus definitions", level: 1, orderNo: 10, description: "Update malicious code protection mechanisms when new releases are available." },
        { code: "L1.11", title: "Perform periodic scans", level: 1, orderNo: 11, description: "Perform periodic scans of the information system and real-time scans of files from external sources." },
        { code: "L1.12", title: "Protect remote access sessions", level: 1, orderNo: 12, description: "Protect the confidentiality of remote access sessions and control remote access through managed access control points." },
        { code: "L1.13", title: "Control use of portable storage", level: 1, orderNo: 13, description: "Establish usage restrictions and implementation guidance for portable storage devices." },
        { code: "L1.14", title: "Conduct security awareness training", level: 1, orderNo: 14, description: "Provide basic security awareness training to all personnel on recognizing and reporting potential threats." },
      ],
    },
    {
      code: "L2",
      title: "Level 2 — Advanced (Protection of CUI)",
      level: 0, orderNo: 2,
      children: [
        { code: "L2.1", title: "Access control enforcement", level: 1, orderNo: 1, description: "Employ the principle of least privilege including specific security functions and privileged accounts." },
        { code: "L2.2", title: "Audit logging", level: 1, orderNo: 2, description: "Create and retain system audit logs and records to enable monitoring, analysis, investigation, and reporting of unlawful or unauthorized activity." },
        { code: "L2.3", title: "Audit log protection", level: 1, orderNo: 3, description: "Protect audit information and audit logging tools from unauthorized access, modification, and deletion." },
        { code: "L2.4", title: "Configuration management", level: 1, orderNo: 4, description: "Establish and maintain baseline configurations and inventories of organizational systems throughout their lifecycles." },
        { code: "L2.5", title: "Configuration change control", level: 1, orderNo: 5, description: "Track, review, approve, and log changes to systems through formal change control processes." },
        { code: "L2.6", title: "Least functionality", level: 1, orderNo: 6, description: "Configure systems to provide only essential capabilities and prohibit or restrict the use of unnecessary functions." },
        { code: "L2.7", title: "Media protection", level: 1, orderNo: 7, description: "Protect system media containing CUI both physically and logically." },
        { code: "L2.8", title: "Media disposal", level: 1, orderNo: 8, description: "Sanitize or destroy system media containing CUI before disposal or release for reuse." },
        { code: "L2.9", title: "Identify and authenticate users", level: 1, orderNo: 9, description: "Employ multi-factor authentication for network access to privileged and non-privileged accounts." },
        { code: "L2.10", title: "Authenticator management", level: 1, orderNo: 10, description: "Manage system authenticators throughout their lifecycle including issuance, renewal, revocation, and destruction." },
        { code: "L2.11", title: "Incident response capability", level: 1, orderNo: 11, description: "Establish and maintain an operational incident handling capability including preparation, detection, analysis, containment, recovery, and user response." },
        { code: "L2.12", title: "Incident reporting", level: 1, orderNo: 12, description: "Track, document, and report incidents to appropriate authorities including the DoD Cyber Crime Center." },
        { code: "L2.13", title: "System and communications protection", level: 1, orderNo: 13, description: "Employ cryptographic mechanisms including FIPS-validated encryption to protect the confidentiality of CUI when transmitted or at rest." },
        { code: "L2.14", title: "Risk management", level: 1, orderNo: 14, description: "Conduct periodic risk assessments to identify, prioritize, and respond to risks to CUI and systems processing CUI." },
        { code: "L2.15", title: "Vulnerability scanning", level: 1, orderNo: 15, description: "Scan for vulnerabilities in systems and applications, remediate findings in accordance with risk assessments." },
        { code: "L2.16", title: "System backup and recovery", level: 1, orderNo: 16, description: "Conduct backups of CUI and system-level information and test recovery procedures periodically." },
        { code: "L2.17", title: "Security awareness training", level: 1, orderNo: 17, description: "Provide role-based security training to personnel with assigned security roles and responsibilities." },
        { code: "L2.18", title: "Personnel security", level: 1, orderNo: 18, description: "Screen personnel prior to authorizing access to CUI and conduct periodic re-screening." },
        { code: "L2.19", title: "Plan of action and milestones", level: 1, orderNo: 19, description: "Develop and maintain a plan of action and milestones (POA&M) to track and remediate security weaknesses." },
      ],
    },
    {
      code: "L3",
      title: "Level 3 — Expert (Reducing Risk from Advanced Threats)",
      level: 0, orderNo: 3,
      children: [
        { code: "L3.1", title: "Advanced persistent threat protection", level: 1, orderNo: 1, description: "Establish and maintain capabilities to detect, deter, and respond to advanced persistent threats (APTs)." },
        { code: "L3.2", title: "Continuous monitoring program", level: 1, orderNo: 2, description: "Implement a comprehensive continuous monitoring program providing real-time awareness of security posture." },
        { code: "L3.3", title: "Advanced audit and accountability", level: 1, orderNo: 3, description: "Implement advanced audit capabilities including behavioral analytics, correlation, and automated response." },
        { code: "L3.4", title: "Supply chain risk management", level: 1, orderNo: 4, description: "Implement a formal supply chain risk management program for systems processing CUI." },
        { code: "L3.5", title: "Advanced configuration management", level: 1, orderNo: 5, description: "Automate configuration management processes and integrate with continuous monitoring capabilities." },
      ],
    },
  ],
};
