import { RegulationSeed } from "./types";

export const COBIT2019_SEED: RegulationSeed = {
  code: "COBIT_2019",
  name: "COBIT 2019",
  type: "framework",
  category: "it_governance",
  jurisdiction: "Global",
  issuer: "ISACA",
  version: "2019",
  description:
    "A comprehensive governance framework for information and technology, providing a systematic approach to managing IT governance and management objectives.",
  effectiveDate: "2019-11-01",
  requirements: [
    {
      code: "EDM",
      title: "Evaluate, Direct and Monitor",
      level: 0, orderNo: 1,
      children: [
        { code: "EDM01", title: "Ensure governance framework setting and maintenance", level: 1, orderNo: 1, description: "Analyze and articulate the requirements for the governance of enterprise I&T, establish and maintain governance structures, and delegate authorities." },
        { code: "EDM02", title: "Ensure benefits delivery", level: 1, orderNo: 2, description: "Optimize the value contribution to the business from business processes, IT services, and IT assets through a portfolio approach." },
        { code: "EDM03", title: "Ensure risk optimization", level: 1, orderNo: 3, description: "Ensure that the enterprise's risk appetite and tolerance are understood, articulated, and communicated, and risk to enterprise value is identified and managed." },
        { code: "EDM04", title: "Ensure resource optimization", level: 1, orderNo: 4, description: "Ensure that adequate and sufficient resources are available to support enterprise strategy and objectives regarding I&T." },
        { code: "EDM05", title: "Ensure stakeholder engagement", level: 1, orderNo: 5, description: "Ensure that stakeholder requirements, needs, and expectations are identified, agreed upon, and met through effective communication and reporting." },
      ],
    },
    {
      code: "APO",
      title: "Align, Plan and Organize",
      level: 0, orderNo: 2,
      children: [
        { code: "APO01", title: "Manage I&T management framework", level: 1, orderNo: 1, description: "Establish and maintain an I&T management framework integrating governance and management processes, organizational structures, roles, and responsibilities." },
        { code: "APO02", title: "Manage strategy", level: 1, orderNo: 2, description: "Define the strategic direction for I&T in alignment with enterprise objectives, covering digital transformation, innovation, and technology roadmaps." },
        { code: "APO03", title: "Manage enterprise architecture", level: 1, orderNo: 3, description: "Establish and maintain an enterprise architecture that enables business transformation and achievement of enterprise goals." },
        { code: "APO04", title: "Manage innovation", level: 1, orderNo: 4, description: "Maintain an understanding of the technology landscape and emerging trends to identify innovation opportunities." },
        { code: "APO05", title: "Manage portfolio", level: 1, orderNo: 5, description: "Execute the strategic direction for I&T investments through a portfolio of programs and projects." },
        { code: "APO06", title: "Manage budget and costs", level: 1, orderNo: 6, description: "Manage the financial resources for I&T through budgeting, cost allocation, and cost optimization processes." },
        { code: "APO07", title: "Manage human resources", level: 1, orderNo: 7, description: "Ensure that human resources are optimized to meet enterprise objectives through workforce planning, competency development, and performance management." },
        { code: "APO08", title: "Manage relationships", level: 1, orderNo: 8, description: "Manage relationships between the I&T function and business stakeholders through formal engagement, communication, and service level management." },
        { code: "APO09", title: "Manage service agreements", level: 1, orderNo: 9, description: "Define, agree upon, and manage I&T services and service levels to support business requirements." },
        { code: "APO10", title: "Manage suppliers", level: 1, orderNo: 10, description: "Manage I&T-related supplier services to meet enterprise requirements through supplier selection, contract management, and performance monitoring." },
        { code: "APO11", title: "Manage quality", level: 1, orderNo: 11, description: "Establish and maintain a quality management system for I&T processes, products, and services consistent with enterprise requirements." },
        { code: "APO12", title: "Manage risk", level: 1, orderNo: 12, description: "Continuously identify, assess, and manage I&T-related risks within the enterprise's risk appetite and tolerance levels." },
        { code: "APO13", title: "Manage security", level: 1, orderNo: 13, description: "Define, operate, and monitor an information security management system aligned with enterprise requirements and security objectives." },
        { code: "APO14", title: "Manage data", level: 1, orderNo: 14, description: "Manage data assets throughout the data life cycle to ensure quality, accessibility, and protection consistent with enterprise requirements." },
      ],
    },
    {
      code: "BAI",
      title: "Build, Acquire and Implement",
      level: 0, orderNo: 3,
      children: [
        { code: "BAI01", title: "Manage programs and projects", level: 1, orderNo: 1, description: "Manage I&T programs and projects throughout the life cycle to deliver value, manage risks, and achieve enterprise objectives." },
        { code: "BAI02", title: "Manage requirements definition", level: 1, orderNo: 2, description: "Identify solution requirements and analyze them in the context of enterprise strategy, business processes, and technology architecture." },
        { code: "BAI03", title: "Manage solutions identification and build", level: 1, orderNo: 3, description: "Design, develop, and acquire I&T solutions in alignment with enterprise requirements and architectural standards." },
        { code: "BAI04", title: "Manage availability and capacity", level: 1, orderNo: 4, description: "Balance current and future needs for availability, performance, and capacity with cost-effective service provision." },
        { code: "BAI05", title: "Manage organizational change", level: 1, orderNo: 5, description: "Maximize the likelihood of successful implementation of organizational change through stakeholder engagement and change enablement." },
        { code: "BAI06", title: "Manage IT changes", level: 1, orderNo: 6, description: "Manage all changes to I&T in a controlled manner including change classification, impact assessment, authorization, and implementation." },
        { code: "BAI07", title: "Manage change acceptance and transitioning", level: 1, orderNo: 7, description: "Formally accept and transition I&T changes into operations including handover planning, knowledge transfer, and operational readiness." },
        { code: "BAI08", title: "Manage knowledge", level: 1, orderNo: 8, description: "Maintain the ability to plan, deliver, and support I&T services through effective knowledge management processes." },
        { code: "BAI09", title: "Manage assets", level: 1, orderNo: 9, description: "Manage I&T assets throughout their life cycle to optimize value, control costs, and support operational and strategic decisions." },
        { code: "BAI10", title: "Manage configuration", level: 1, orderNo: 10, description: "Define and maintain configuration information about I&T assets and services to support reliable service management." },
      ],
    },
    {
      code: "DSS",
      title: "Deliver, Service and Support",
      level: 0, orderNo: 4,
      children: [
        { code: "DSS01", title: "Manage operations", level: 1, orderNo: 1, description: "Coordinate and execute I&T operational activities and procedures to deliver and support IT services at agreed levels." },
        { code: "DSS02", title: "Manage service requests and incidents", level: 1, orderNo: 2, description: "Respond to service requests and resolve incidents in a timely manner to restore normal service operation." },
        { code: "DSS03", title: "Manage problems", level: 1, orderNo: 3, description: "Identify and resolve root causes of incidents to prevent recurrence and minimize business impact." },
        { code: "DSS04", title: "Manage continuity", level: 1, orderNo: 4, description: "Establish and maintain business continuity and IT disaster recovery plans to ensure continuous availability of critical services." },
        { code: "DSS05", title: "Manage security services", level: 1, orderNo: 5, description: "Protect enterprise information and IT assets through security operations including monitoring, vulnerability management, and incident response." },
        { code: "DSS06", title: "Manage business process controls", level: 1, orderNo: 6, description: "Define and maintain business process controls to ensure that information related to business processes meets required quality and compliance standards." },
      ],
    },
    {
      code: "MEA",
      title: "Monitor, Evaluate and Assess",
      level: 0, orderNo: 5,
      children: [
        { code: "MEA01", title: "Manage performance and conformance monitoring", level: 1, orderNo: 1, description: "Collect, validate, and evaluate I&T performance and conformance metrics and monitor progress against objectives." },
        { code: "MEA02", title: "Manage system of internal control", level: 1, orderNo: 2, description: "Monitor and evaluate the effectiveness of the internal control system for I&T including control design and operating effectiveness." },
        { code: "MEA03", title: "Manage compliance with external requirements", level: 1, orderNo: 3, description: "Identify, monitor, and report on compliance with applicable laws, regulations, and contractual requirements related to I&T." },
        { code: "MEA04", title: "Manage assurance", level: 1, orderNo: 4, description: "Plan, scope, and coordinate assurance activities covering I&T governance and management processes to provide independent validation." },
      ],
    },
  ],
};
