import { RegulationSeed } from "./types";

export const FEDRAMP_SEED: RegulationSeed = {
  code: "FEDRAMP",
  name: "Federal Risk and Authorization Management Program",
  type: "standard",
  category: "information_security",
  jurisdiction: "US",
  issuer: "General Services Administration / Joint Authorization Board",
  version: "Rev. 5 (NIST 800-53 based)",
  description:
    "FedRAMP is a US government-wide program that provides a standardized approach to security assessment, authorization, and continuous monitoring for cloud products and services. FedRAMP leverages NIST SP 800-53 controls and defines baseline control sets for low, moderate, and high impact levels.",
  effectiveDate: "2022-12-01",
  requirements: [
    {
      code: "AC",
      title: "Access Control (AC) Family",
      level: 0, orderNo: 1,
      children: [
        { code: "AC-1", title: "Access control policy and procedures", level: 1, orderNo: 1, description: "Develop, disseminate, and periodically review formal access control policies and procedures aligned with FedRAMP requirements." },
        { code: "AC-2", title: "Account management", level: 1, orderNo: 2, description: "Manage system accounts including identification, authorization, expiration, review, and termination of accounts." },
        { code: "AC-3", title: "Access enforcement", level: 1, orderNo: 3, description: "Enforce approved authorizations for logical access to the system in accordance with policy." },
        { code: "AC-4", title: "Information flow enforcement", level: 1, orderNo: 4, description: "Enforce approved authorizations for controlling the flow of information within the system." },
        { code: "AC-5", title: "Separation of duties", level: 1, orderNo: 5, description: "Enforce separation of duties through assigned access authorizations." },
        { code: "AC-6", title: "Least privilege", level: 1, orderNo: 6, description: "Employ the principle of least privilege, allowing only authorized access for users necessary to accomplish assigned tasks." },
        { code: "AC-7", title: "Unsuccessful logon attempts", level: 1, orderNo: 7, description: "Enforce a limit of consecutive invalid logon attempts and automatically lock the account for a defined period." },
        { code: "AC-8", title: "System use notification", level: 1, orderNo: 8, description: "Display system use notifications before granting access to the system." },
        { code: "AC-17", title: "Remote access", level: 1, orderNo: 9, description: "Establish and document usage restrictions and implement controls for remote access sessions." },
        { code: "AC-18", title: "Wireless access", level: 1, orderNo: 10, description: "Establish usage restrictions and implement controls for wireless access to the system." },
      ],
    },
    {
      code: "AU",
      title: "Audit and Accountability (AU) Family",
      level: 0, orderNo: 2,
      children: [
        { code: "AU-1", title: "Audit and accountability policy", level: 1, orderNo: 1, description: "Develop and maintain audit and accountability policies and procedures." },
        { code: "AU-2", title: "Audit events", level: 1, orderNo: 2, description: "Identify and define auditable events and coordinate with other organizational entities." },
        { code: "AU-3", title: "Content of audit records", level: 1, orderNo: 3, description: "Ensure audit records contain sufficient information to determine what events occurred, sources, outcomes, and identity." },
        { code: "AU-4", title: "Audit log storage capacity", level: 1, orderNo: 4, description: "Allocate sufficient audit log storage capacity and configure alerting when capacity is reached." },
        { code: "AU-5", title: "Response to audit processing failures", level: 1, orderNo: 5, description: "Alert personnel upon audit processing failure and take appropriate actions." },
        { code: "AU-6", title: "Audit review, analysis, and reporting", level: 1, orderNo: 6, description: "Review and analyze audit records for indications of inappropriate or unusual activity on a regular basis." },
        { code: "AU-7", title: "Audit reduction and report generation", level: 1, orderNo: 7, description: "Provide and support an audit reduction and report generation capability." },
        { code: "AU-8", title: "Time stamps", level: 1, orderNo: 8, description: "Use internal system clocks to generate time stamps for audit records and synchronize to authoritative time source." },
        { code: "AU-12", title: "Audit generation", level: 1, orderNo: 9, description: "Provide audit record generation capability for the defined auditable events." },
      ],
    },
    {
      code: "CM",
      title: "Configuration Management (CM) Family",
      level: 0, orderNo: 3,
      children: [
        { code: "CM-1", title: "Configuration management policy", level: 1, orderNo: 1, description: "Develop and maintain configuration management policies and procedures." },
        { code: "CM-2", title: "Baseline configuration", level: 1, orderNo: 2, description: "Develop and maintain baseline configurations of the system under configuration control." },
        { code: "CM-3", title: "Configuration change control", level: 1, orderNo: 3, description: "Track, review, approve, and log changes to the system through formal change control." },
        { code: "CM-4", title: "Impact analysis of changes", level: 1, orderNo: 4, description: "Analyze changes to the system for potential security impacts prior to implementation." },
        { code: "CM-5", title: "Access restrictions for change", level: 1, orderNo: 5, description: "Define and enforce access restrictions for changes to the system." },
        { code: "CM-6", title: "Configuration settings", level: 1, orderNo: 6, description: "Establish and enforce configuration settings for IT products using security configuration checklists." },
        { code: "CM-7", title: "Least functionality", level: 1, orderNo: 7, description: "Configure the system to provide only essential capabilities and disable unnecessary functions." },
        { code: "CM-8", title: "System component inventory", level: 1, orderNo: 8, description: "Develop and maintain an inventory of system components and location." },
      ],
    },
    {
      code: "CP",
      title: "Contingency Planning (CP) Family",
      level: 0, orderNo: 4,
      children: [
        { code: "CP-1", title: "Contingency planning policy", level: 1, orderNo: 1, description: "Develop and maintain contingency planning policies and procedures." },
        { code: "CP-2", title: "Contingency plan", level: 1, orderNo: 2, description: "Develop and maintain a contingency plan for the system to address emergency situations." },
        { code: "CP-3", title: "Contingency training", level: 1, orderNo: 3, description: "Provide contingency training to personnel with roles and responsibilities in contingency operations." },
        { code: "CP-4", title: "Contingency plan testing", level: 1, orderNo: 4, description: "Test the contingency plan at least annually to determine its effectiveness." },
        { code: "CP-7", title: "Alternate processing site", level: 1, orderNo: 5, description: "Establish an alternate processing site for essential mission and business functions." },
        { code: "CP-9", title: "System backup", level: 1, orderNo: 6, description: "Conduct backups of user-level and system-level information and protect backup media." },
        { code: "CP-10", title: "System recovery and reconstitution", level: 1, orderNo: 7, description: "Implement procedures for system recovery and reconstitution after disruption." },
      ],
    },
    {
      code: "IR",
      title: "Incident Response (IR) Family",
      level: 0, orderNo: 5,
      children: [
        { code: "IR-1", title: "Incident response policy", level: 1, orderNo: 1, description: "Develop and maintain incident response policies and procedures." },
        { code: "IR-2", title: "Incident response training", level: 1, orderNo: 2, description: "Provide incident response training to personnel with incident response roles." },
        { code: "IR-3", title: "Incident response testing", level: 1, orderNo: 3, description: "Test the incident response capability at least annually using tests and exercises." },
        { code: "IR-4", title: "Incident handling", level: 1, orderNo: 4, description: "Implement incident handling capability for detection, analysis, containment, eradication, and recovery." },
        { code: "IR-5", title: "Incident monitoring", level: 1, orderNo: 5, description: "Track and document system security incidents and monitor for incident trends." },
        { code: "IR-6", title: "Incident reporting", level: 1, orderNo: 6, description: "Require personnel to report suspected security incidents and report to organizational incident response." },
        { code: "IR-7", title: "Incident response assistance", level: 1, orderNo: 7, description: "Provide an incident response support resource and offer assistance to users." },
      ],
    },
    {
      code: "RA",
      title: "Risk Assessment (RA) Family",
      level: 0, orderNo: 6,
      children: [
        { code: "RA-1", title: "Risk assessment policy", level: 1, orderNo: 1, description: "Develop and maintain risk assessment policies and procedures." },
        { code: "RA-2", title: "Security categorization", level: 1, orderNo: 2, description: "Categorize the system and information according to FIPS 199 standards." },
        { code: "RA-3", title: "Risk assessment", level: 1, orderNo: 3, description: "Conduct risk assessments to identify threats, vulnerabilities, and impact to the organization." },
        { code: "RA-5", title: "Vulnerability scanning", level: 1, orderNo: 4, description: "Scan for vulnerabilities in the system and hosted applications, remediate findings, and share scan results with FedRAMP." },
        { code: "RA-7", title: "Risk response", level: 1, orderNo: 5, description: "Respond to risk assessment findings using a prioritized risk remediation approach." },
      ],
    },
    {
      code: "SC",
      title: "System and Communications Protection (SC) Family",
      level: 0, orderNo: 7,
      children: [
        { code: "SC-1", title: "System and communications protection policy", level: 1, orderNo: 1, description: "Develop and maintain system and communications protection policies and procedures." },
        { code: "SC-7", title: "Boundary protection", level: 1, orderNo: 2, description: "Monitor and control communications at the external boundary and key internal boundaries." },
        { code: "SC-8", title: "Transmission confidentiality and integrity", level: 1, orderNo: 3, description: "Protect the confidentiality and integrity of transmitted information." },
        { code: "SC-12", title: "Cryptographic key management", level: 1, orderNo: 4, description: "Establish and maintain a cryptographic key management capability." },
        { code: "SC-13", title: "Cryptographic protection", level: 1, orderNo: 5, description: "Use FIPS-validated cryptography for specified cryptographic uses." },
        { code: "SC-28", title: "Protection of information at rest", level: 1, orderNo: 6, description: "Protect the confidentiality and integrity of information at rest." },
      ],
    },
    {
      code: "SI",
      title: "System and Information Integrity (SI) Family",
      level: 0, orderNo: 8,
      children: [
        { code: "SI-1", title: "System and information integrity policy", level: 1, orderNo: 1, description: "Develop and maintain system and information integrity policies and procedures." },
        { code: "SI-2", title: "Flaw remediation", level: 1, orderNo: 2, description: "Identify, report, and correct system flaws in a timely manner." },
        { code: "SI-3", title: "Malicious code protection", level: 1, orderNo: 3, description: "Implement malicious code protection mechanisms at system entry and exit points." },
        { code: "SI-4", title: "System monitoring", level: 1, orderNo: 4, description: "Monitor the system to detect attacks and indicators of potential compromise." },
        { code: "SI-5", title: "Security alerts and advisories", level: 1, orderNo: 5, description: "Receive and respond to security alerts and advisories from external organizations." },
        { code: "SI-7", title: "Software and information integrity", level: 1, orderNo: 6, description: "Detect and respond to unauthorized changes to software and information." },
        { code: "SI-12", title: "Information handling", level: 1, orderNo: 7, description: "Handle and retain output from the system in accordance with policy." },
      ],
    },
  ],
};
