import { RegulationSeed } from "./types";

export const NIST_SP_800_53_SEED: RegulationSeed = {
  code: "NIST_SP_800_53",
  name: "NIST Special Publication 800-53 Rev 5",
  type: "standard",
  category: "information_security",
  jurisdiction: "US",
  issuer: "NIST",
  version: "Rev 5",
  description:
    "Security and Privacy Controls for Information Systems and Organizations, providing a comprehensive catalog of controls for federal information systems and organizations.",
  effectiveDate: "2020-09-23",
  requirements: [
    {
      code: "AC",
      title: "Access Control",
      level: 0, orderNo: 1,
      children: [
        { code: "AC-1", title: "Access Control Policy and Procedures", level: 1, orderNo: 1, description: "Develop, document, and disseminate an access control policy that addresses purpose, scope, roles, responsibilities, and compliance." },
        { code: "AC-2", title: "Account Management", level: 1, orderNo: 2, description: "Manage information system accounts including identification, authorization, notification, review, and termination of accounts." },
        { code: "AC-3", title: "Access Enforcement", level: 1, orderNo: 3, description: "Enforce approved authorizations for logical access to information and system resources in accordance with applicable policies." },
        { code: "AC-4", title: "Information Flow Enforcement", level: 1, orderNo: 4, description: "Enforce approved authorizations for controlling the flow of information within the system and between interconnected systems." },
        { code: "AC-5", title: "Separation of Duties", level: 1, orderNo: 5, description: "Separate duties of individuals as necessary to prevent malevolent activity without collusion." },
        { code: "AC-6", title: "Least Privilege", level: 1, orderNo: 6, description: "Employ the principle of least privilege, allowing only authorized access necessary to accomplish assigned tasks." },
        { code: "AC-7", title: "Unsuccessful Logon Attempts", level: 1, orderNo: 7, description: "Enforce a limit of consecutive invalid logon attempts by a user during a defined time period." },
        { code: "AC-8", title: "System Use Notification", level: 1, orderNo: 8, description: "Display system use notification messages before granting access to the system." },
        { code: "AC-17", title: "Remote Access", level: 1, orderNo: 9, description: "Establish and document usage restrictions and implementation guidance for remote access to information systems." },
        { code: "AC-18", title: "Wireless Access", level: 1, orderNo: 10, description: "Establish usage restrictions and implementation guidance for wireless access to the information system." },
        { code: "AC-20", title: "Use of External Information Systems", level: 1, orderNo: 11, description: "Establish terms and conditions for authorized individuals to use external information systems." },
      ],
    },
    {
      code: "AU",
      title: "Audit and Accountability",
      level: 0, orderNo: 2,
      children: [
        { code: "AU-1", title: "Audit and Accountability Policy and Procedures", level: 1, orderNo: 1, description: "Develop and disseminate an audit and accountability policy that addresses purpose, scope, roles, and compliance." },
        { code: "AU-2", title: "Audit Events", level: 1, orderNo: 2, description: "Determine which audit events are to be audited and coordinate with other organizational entities." },
        { code: "AU-3", title: "Content of Audit Records", level: 1, orderNo: 3, description: "Ensure audit records contain sufficient information to determine what event occurred, source, outcome, and identity." },
        { code: "AU-4", title: "Audit Log Storage Capacity", level: 1, orderNo: 4, description: "Allocate audit log storage capacity and configure auditing to reduce the likelihood of storage capacity being exceeded." },
        { code: "AU-5", title: "Response to Audit Processing Failures", level: 1, orderNo: 5, description: "Alert designated organizational officials within an organization-defined time period of audit processing failures." },
        { code: "AU-6", title: "Audit Review, Analysis, and Reporting", level: 1, orderNo: 6, description: "Review and analyze audit records on an ongoing basis for indications of inappropriate or unusual activity." },
        { code: "AU-7", title: "Audit Reduction and Report Generation", level: 1, orderNo: 7, description: "Provide and implement an audit reduction and report generation capability that supports on-demand and automated reports." },
        { code: "AU-8", title: "Time Stamps", level: 1, orderNo: 8, description: "Generate time stamps for audit records using internal system clocks synchronized to an authoritative time source." },
        { code: "AU-9", title: "Protection of Audit Information", level: 1, orderNo: 9, description: "Protect audit information and audit tools from unauthorized access, modification, and deletion." },
        { code: "AU-11", title: "Audit Record Retention", level: 1, orderNo: 10, description: "Retain audit records for an organization-defined time period to support incident investigations and compliance." },
      ],
    },
    {
      code: "AT",
      title: "Awareness and Training",
      level: 0, orderNo: 3,
      children: [
        { code: "AT-1", title: "Awareness and Training Policy and Procedures", level: 1, orderNo: 1, description: "Develop and disseminate an awareness and training policy that addresses purpose, scope, roles, and compliance." },
        { code: "AT-2", title: "Literacy Training and Awareness", level: 1, orderNo: 2, description: "Provide security and privacy literacy training to all personnel including basic security practices and role-specific training." },
        { code: "AT-3", title: "Role-Based Training", level: 1, orderNo: 3, description: "Provide role-based security and privacy training to personnel with assigned roles before authorizing access or performing assigned duties." },
        { code: "AT-4", title: "Training Records", level: 1, orderNo: 4, description: "Document and monitor individual information security and privacy training activities including completion and effectiveness." },
      ],
    },
    {
      code: "CM",
      title: "Configuration Management",
      level: 0, orderNo: 4,
      children: [
        { code: "CM-1", title: "Configuration Management Policy and Procedures", level: 1, orderNo: 1, description: "Develop and disseminate a configuration management policy addressing purpose, scope, roles, and compliance." },
        { code: "CM-2", title: "Baseline Configuration", level: 1, orderNo: 2, description: "Develop and maintain baseline configurations of information systems including hardware, software, and firmware." },
        { code: "CM-3", title: "Configuration Change Control", level: 1, orderNo: 3, description: "Manage changes to information systems through formal change control procedures including approval and documentation." },
        { code: "CM-4", title: "Impact Analyses", level: 1, orderNo: 4, description: "Analyze changes to the information system to determine potential security and privacy impacts before implementation." },
        { code: "CM-5", title: "Access Restrictions for Change", level: 1, orderNo: 5, description: "Define, document, and enforce physical and logical access restrictions associated with changes to the information system." },
        { code: "CM-6", title: "Configuration Settings", level: 1, orderNo: 6, description: "Establish and enforce configuration settings for information technology products employed in information systems." },
        { code: "CM-7", title: "Least Functionality", level: 1, orderNo: 7, description: "Configure information systems to provide only essential capabilities and prohibit or restrict nonessential functions." },
        { code: "CM-8", title: "System Component Inventory", level: 1, orderNo: 8, description: "Develop and maintain an inventory of system components that is accurate, complete, and current." },
        { code: "CM-9", title: "Configuration Management Plan", level: 1, orderNo: 9, description: "Develop and implement a configuration management plan for the information system." },
      ],
    },
    {
      code: "CP",
      title: "Contingency Planning",
      level: 0, orderNo: 5,
      children: [
        { code: "CP-1", title: "Contingency Planning Policy and Procedures", level: 1, orderNo: 1, description: "Develop and disseminate a contingency planning policy addressing purpose, scope, roles, and compliance." },
        { code: "CP-2", title: "Contingency Plan", level: 1, orderNo: 2, description: "Develop and implement a contingency plan for the information system addressing essential mission and business functions." },
        { code: "CP-3", title: "Contingency Training", level: 1, orderNo: 3, description: "Provide contingency training to personnel with contingency roles and responsibilities within an organization-defined time period." },
        { code: "CP-4", title: "Contingency Plan Testing", level: 1, orderNo: 4, description: "Test the contingency plan at an organization-defined frequency to determine effectiveness and maintain readiness." },
        { code: "CP-6", title: "Alternate Storage Site", level: 1, orderNo: 5, description: "Establish an alternate storage site including necessary agreements to store and retrieve system backup information." },
        { code: "CP-7", title: "Alternate Processing Site", level: 1, orderNo: 6, description: "Establish an alternate processing site including necessary agreements to permit transfer and resumption of operations." },
        { code: "CP-8", title: "Telecommunications Services", level: 1, orderNo: 7, description: "Establish alternate telecommunications services for primary telecommunications capabilities." },
        { code: "CP-9", title: "System Backup", level: 1, orderNo: 8, description: "Back up user-level and system-level information contained in the information system including system state information." },
        { code: "CP-10", title: "System Recovery and Reconstitution", level: 1, orderNo: 9, description: "Implement mechanisms to recover and reconstitute the information system to a known state after disruption or failure." },
      ],
    },
    {
      code: "IA",
      title: "Identification and Authentication",
      level: 0, orderNo: 6,
      children: [
        { code: "IA-1", title: "Identification and Authentication Policy", level: 1, orderNo: 1, description: "Develop and disseminate an identification and authentication policy addressing purpose, scope, roles, and compliance." },
        { code: "IA-2", title: "Identification and Authentication Users", level: 1, orderNo: 2, description: "Uniquely identify and authenticate users or processes acting on behalf of users as a precondition to access." },
        { code: "IA-3", title: "Device Identification and Authentication", level: 1, orderNo: 3, description: "Uniquely identify and authenticate devices before establishing connections to the information system." },
        { code: "IA-4", title: "Identifier Management", level: 1, orderNo: 4, description: "Manage information system identifiers by receiving authorization, selecting an identifier, and issuing the identifier." },
        { code: "IA-5", title: "Authenticator Management", level: 1, orderNo: 5, description: "Manage information system authenticators by establishing initial authenticator content, changing authenticators, and revoking authenticators." },
        { code: "IA-6", title: "Authenticator Feedback", level: 1, orderNo: 6, description: "Obscure feedback of authentication information during the authentication process to protect from unauthorized disclosure." },
        { code: "IA-7", title: "Cryptographic Module Authentication", level: 1, orderNo: 7, description: "Implement mechanisms for authentication to a cryptographic module that meet applicable federal laws and standards." },
        { code: "IA-8", title: "Identification and Authentication for Non-Organizational Users", level: 1, orderNo: 8, description: "Uniquely identify and authenticate non-organizational users or processes acting on behalf of those users." },
      ],
    },
    {
      code: "IR",
      title: "Incident Response",
      level: 0, orderNo: 7,
      children: [
        { code: "IR-1", title: "Incident Response Policy and Procedures", level: 1, orderNo: 1, description: "Develop and disseminate an incident response policy addressing purpose, scope, roles, and compliance." },
        { code: "IR-2", title: "Incident Response Training", level: 1, orderNo: 2, description: "Provide incident response training to personnel with incident response roles within an organization-defined time period." },
        { code: "IR-3", title: "Incident Response Testing", level: 1, orderNo: 3, description: "Test the incident response capability for the information system at an organization-defined frequency." },
        { code: "IR-4", title: "Incident Handling", level: 1, orderNo: 4, description: "Implement incident handling capability for incidents consistent with the response plan including preparation, detection, analysis, containment, and recovery." },
        { code: "IR-5", title: "Incident Monitoring", level: 1, orderNo: 5, description: "Track and document information system security incidents on an ongoing basis." },
        { code: "IR-6", title: "Incident Reporting", level: 1, orderNo: 6, description: "Require personnel to report suspected security incidents within an organization-defined time period." },
        { code: "IR-7", title: "Incident Response Assistance", level: 1, orderNo: 7, description: "Provide an incident response support resource that offers advice and assistance to users." },
        { code: "IR-8", title: "Incident Response Plan", level: 1, orderNo: 8, description: "Develop and maintain a formal incident response plan that defines roles, phases, and coordination activities." },
      ],
    },
    {
      code: "MA",
      title: "Maintenance",
      level: 0, orderNo: 8,
      children: [
        { code: "MA-1", title: "Maintenance Policy and Procedures", level: 1, orderNo: 1, description: "Develop and disseminate a system maintenance policy addressing purpose, scope, roles, and compliance." },
        { code: "MA-2", title: "Controlled Maintenance", level: 1, orderNo: 2, description: "Schedule, document, and review records of maintenance on information system components." },
        { code: "MA-3", title: "Maintenance Tools", level: 1, orderNo: 3, description: "Approve, control, and monitor the use of information system maintenance tools." },
        { code: "MA-4", title: "Nonlocal Maintenance", level: 1, orderNo: 4, description: "Authorize, monitor, and control nonlocal maintenance and diagnostic activities." },
        { code: "MA-5", title: "Maintenance Personnel", level: 1, orderNo: 5, description: "Establish a process for maintenance personnel authorization and ensure personnel have required access authorizations." },
        { code: "MA-6", title: "Timely Maintenance", level: 1, orderNo: 6, description: "Obtain maintenance support and spare parts within an organization-defined time period of failure." },
      ],
    },
    {
      code: "MP",
      title: "Media Protection",
      level: 0, orderNo: 9,
      children: [
        { code: "MP-1", title: "Media Protection Policy and Procedures", level: 1, orderNo: 1, description: "Develop and disseminate a media protection policy addressing purpose, scope, roles, and compliance." },
        { code: "MP-2", title: "Media Access", level: 1, orderNo: 2, description: "Restrict access to digital and nondigital media in accordance with the assigned classification or sensitivity level." },
        { code: "MP-3", title: "Media Marking", level: 1, orderNo: 3, description: "Mark information system media indicating the distribution limitations, handling caveats, and applicable security markings." },
        { code: "MP-4", title: "Media Storage", level: 1, orderNo: 4, description: "Physically control and securely store digital and nondigital media within controlled areas." },
        { code: "MP-5", title: "Media Transport", level: 1, orderNo: 5, description: "Protect and control digital and nondigital media during transport outside controlled areas." },
        { code: "MP-6", title: "Media Sanitization", level: 1, orderNo: 6, description: "Sanitize information system media before disposal, release out of organizational control, or release for reuse." },
        { code: "MP-7", title: "Media Use", level: 1, orderNo: 7, description: "Restrict or prohibit the use of portable storage devices on information systems." },
      ],
    },
    {
      code: "PE",
      title: "Physical and Environmental Protection",
      level: 0, orderNo: 10,
      children: [
        { code: "PE-1", title: "Physical Protection Policy and Procedures", level: 1, orderNo: 1, description: "Develop and disseminate a physical and environmental protection policy addressing purpose, scope, roles, and compliance." },
        { code: "PE-2", title: "Physical Access Authorizations", level: 1, orderNo: 2, description: "Develop and keep current a list of personnel with authorized access to the facility where the information system resides." },
        { code: "PE-3", title: "Physical Access Control", level: 1, orderNo: 3, description: "Enforce physical access authorizations at all entry and exit points to facilities and spaces containing information systems." },
        { code: "PE-4", title: "Access Control for Transmission", level: 1, orderNo: 4, description: "Control physical access to information system distribution and transmission lines within organizational facilities." },
        { code: "PE-5", title: "Access Control for Output Devices", level: 1, orderNo: 5, description: "Control physical access to information system output devices to prevent unauthorized individuals from obtaining output." },
        { code: "PE-6", title: "Monitoring Physical Access", level: 1, orderNo: 6, description: "Monitor physical access to the facility where the information system resides to detect and respond to incidents." },
        { code: "PE-8", title: "Visitor Access Records", level: 1, orderNo: 7, description: "Maintain visitor access records to the facility where the information system resides." },
        { code: "PE-9", title: "Power Equipment and Cabling", level: 1, orderNo: 8, description: "Protect power equipment and power cabling for the information system from damage and destruction." },
        { code: "PE-10", title: "Emergency Shutoff", level: 1, orderNo: 9, description: "Provide emergency shutoff capabilities for the information system and individual system components." },
        { code: "PE-11", title: "Emergency Power", level: 1, orderNo: 10, description: "Provide a short-term uninterruptible power supply to facilitate orderly shutdown or transition to long-term power." },
        { code: "PE-12", title: "Emergency Lighting", level: 1, orderNo: 11, description: "Employ and maintain automatic emergency lighting for all information system areas." },
        { code: "PE-13", title: "Fire Protection", level: 1, orderNo: 12, description: "Employ and maintain fire detection and suppression systems for facilities containing information systems." },
        { code: "PE-14", title: "Temperature and Humidity Controls", level: 1, orderNo: 13, description: "Maintain temperature and humidity levels within facilities containing information systems." },
      ],
    },
    {
      code: "PL",
      title: "Planning",
      level: 0, orderNo: 11,
      children: [
        { code: "PL-1", title: "Planning Policy and Procedures", level: 1, orderNo: 1, description: "Develop and disseminate a security and privacy planning policy addressing purpose, scope, roles, and compliance." },
        { code: "PL-2", title: "System Security and Privacy Plans", level: 1, orderNo: 2, description: "Develop and implement security and privacy plans for the information system that describe the controls in place." },
        { code: "PL-4", title: "Rules of Behavior", level: 1, orderNo: 3, description: "Establish and make readily available to all personnel rules of behavior describing responsibilities and expected behavior." },
        { code: "PL-8", title: "Security and Privacy Architectures", level: 1, orderNo: 4, description: "Develop and maintain security and privacy architectures that integrate with the enterprise architecture." },
        { code: "PL-9", title: "Central Management", level: 1, orderNo: 5, description: "Centrally manage security and privacy controls that affect the information system." },
      ],
    },
    {
      code: "PS",
      title: "Personnel Security",
      level: 0, orderNo: 12,
      children: [
        { code: "PS-1", title: "Personnel Security Policy and Procedures", level: 1, orderNo: 1, description: "Develop and disseminate a personnel security policy addressing purpose, scope, roles, and compliance." },
        { code: "PS-2", title: "Position Risk Designation", level: 1, orderNo: 2, description: "Assign risk designations to all organizational positions and establish screening criteria." },
        { code: "PS-3", title: "Personnel Screening", level: 1, orderNo: 3, description: "Screen individuals before authorizing access to the information system consistent with risk designations." },
        { code: "PS-4", title: "Personnel Termination", level: 1, orderNo: 4, description: "Terminate information system access upon personnel termination and conduct exit interviews." },
        { code: "PS-5", title: "Personnel Transfer", level: 1, orderNo: 5, description: "Review and reconfigure logical and physical access authorizations when personnel are reassigned or transferred." },
        { code: "PS-6", title: "Access Agreements", level: 1, orderNo: 6, description: "Ensure personnel sign appropriate access agreements before being granted access to the information system." },
        { code: "PS-7", title: "Third-Party Personnel Security", level: 1, orderNo: 7, description: "Establish personnel security requirements for third-party providers consistent with organizational screening." },
        { code: "PS-8", title: "Personnel Sanctions", level: 1, orderNo: 8, description: "Employ formal sanctions for personnel failing to comply with security and privacy policies." },
      ],
    },
    {
      code: "RA",
      title: "Risk Assessment",
      level: 0, orderNo: 13,
      children: [
        { code: "RA-1", title: "Risk Assessment Policy and Procedures", level: 1, orderNo: 1, description: "Develop and disseminate a risk assessment policy addressing purpose, scope, roles, and compliance." },
        { code: "RA-2", title: "Security Categorization", level: 1, orderNo: 2, description: "Categorize information and the information system in accordance with applicable laws and regulations." },
        { code: "RA-3", title: "Risk Assessment", level: 1, orderNo: 3, description: "Conduct risk assessments on the information system and the information it processes, stores, or transmits." },
        { code: "RA-5", title: "Vulnerability Monitoring and Scanning", level: 1, orderNo: 4, description: "Monitor and scan for vulnerabilities in the information system and hosted applications on an ongoing basis." },
        { code: "RA-6", title: "Technical Surveillance Countermeasures", level: 1, orderNo: 5, description: "Employ technical surveillance countermeasures to detect and neutralize technical penetrations." },
        { code: "RA-7", title: "Risk Response", level: 1, orderNo: 6, description: "Respond to risk assessment findings and recommendations using defined risk response options." },
        { code: "RA-9", title: "Criticality Analysis", level: 1, orderNo: 7, description: "Identify critical information system components and functions by performing criticality analysis." },
        { code: "RA-10", title: "Threat Hunting", level: 1, orderNo: 8, description: "Establish and maintain a threat hunting capability to proactively search for indicators of compromise." },
      ],
    },
    {
      code: "CA",
      title: "Security Assessment and Authorization",
      level: 0, orderNo: 14,
      children: [
        { code: "CA-1", title: "Assessment and Authorization Policies", level: 1, orderNo: 1, description: "Develop and disseminate assessment and authorization policies addressing purpose, scope, roles, and compliance." },
        { code: "CA-2", title: "Control Assessments", level: 1, orderNo: 2, description: "Assess the security and privacy controls in the information system at an organization-defined frequency." },
        { code: "CA-3", title: "System Interconnections", level: 1, orderNo: 3, description: "Authorize connections from the information system to other systems through formal interconnection agreements." },
        { code: "CA-5", title: "Plan of Action and Milestones", level: 1, orderNo: 4, description: "Develop and maintain a plan of action and milestones to track remediation of control deficiencies." },
        { code: "CA-6", title: "Authorization", level: 1, orderNo: 5, description: "Authorize the information system for processing before commencing operations and reauthorize at defined intervals." },
        { code: "CA-7", title: "Continuous Monitoring", level: 1, orderNo: 6, description: "Develop and implement a continuous monitoring strategy for the information system." },
        { code: "CA-8", title: "Penetration Testing", level: 1, orderNo: 7, description: "Conduct penetration testing on the information system at an organization-defined frequency." },
        { code: "CA-9", title: "Internal System Connections", level: 1, orderNo: 8, description: "Authorize internal connections of system components to the information system." },
      ],
    },
    {
      code: "SC",
      title: "System and Communications Protection",
      level: 0, orderNo: 15,
      children: [
        { code: "SC-1", title: "System Protection Policy and Procedures", level: 1, orderNo: 1, description: "Develop and disseminate a system and communications protection policy addressing purpose, scope, roles, and compliance." },
        { code: "SC-2", title: "Application Partitioning", level: 1, orderNo: 2, description: "Separate user functionality from information system management functionality." },
        { code: "SC-4", title: "Information in Shared Resources", level: 1, orderNo: 3, description: "Prevent unauthorized and unintended information transfer via shared system resources." },
        { code: "SC-5", title: "Denial of Service Protection", level: 1, orderNo: 4, description: "Protect against or limit the effects of denial of service attacks on the information system." },
        { code: "SC-7", title: "Boundary Protection", level: 1, orderNo: 5, description: "Monitor and control communications at the external boundary of the system and at key internal boundaries." },
        { code: "SC-8", title: "Transmission Confidentiality and Integrity", level: 1, orderNo: 6, description: "Protect the confidentiality and integrity of transmitted information." },
        { code: "SC-10", title: "Network Disconnect", level: 1, orderNo: 7, description: "Terminate network connections associated with communications sessions at the end of sessions or after defined inactivity." },
        { code: "SC-12", title: "Cryptographic Key Management", level: 1, orderNo: 8, description: "Establish and manage cryptographic keys for required cryptography employed in the information system." },
        { code: "SC-13", title: "Cryptographic Protection", level: 1, orderNo: 9, description: "Implement cryptographic mechanisms to prevent unauthorized disclosure of information and detect changes." },
        { code: "SC-15", title: "Collaborative Computing Devices", level: 1, orderNo: 10, description: "Prohibit remote activation of collaborative computing devices and provide explicit indication of use." },
        { code: "SC-20", title: "Secure Name/Address Resolution", level: 1, orderNo: 11, description: "Provide additional data origin authentication and integrity verification for name/address resolution services." },
        { code: "SC-28", title: "Protection of Information at Rest", level: 1, orderNo: 12, description: "Protect the confidentiality and integrity of information at rest." },
        { code: "SC-39", title: "Process Isolation", level: 1, orderNo: 13, description: "Maintain a separate execution domain for each executing process in the information system." },
      ],
    },
    {
      code: "SI",
      title: "System and Information Integrity",
      level: 0, orderNo: 16,
      children: [
        { code: "SI-1", title: "Integrity Policy and Procedures", level: 1, orderNo: 1, description: "Develop and disseminate a system and information integrity policy addressing purpose, scope, roles, and compliance." },
        { code: "SI-2", title: "Flaw Remediation", level: 1, orderNo: 2, description: "Identify, report, and correct information system flaws within an organization-defined time period." },
        { code: "SI-3", title: "Malicious Code Protection", level: 1, orderNo: 3, description: "Implement malicious code protection mechanisms at system entry and exit points to detect and eradicate malicious code." },
        { code: "SI-4", title: "System Monitoring", level: 1, orderNo: 4, description: "Monitor the information system to detect attacks and indicators of potential attacks." },
        { code: "SI-5", title: "Security Alerts and Advisories", level: 1, orderNo: 5, description: "Receive information system security alerts and advisories and disseminate them to appropriate personnel." },
        { code: "SI-6", title: "Security and Privacy Function Verification", level: 1, orderNo: 6, description: "Verify the correct operation of security and privacy functions at an organization-defined frequency." },
        { code: "SI-7", title: "Software and Firmware Integrity", level: 1, orderNo: 7, description: "Detect unauthorized changes to software and firmware using integrity verification tools." },
        { code: "SI-8", title: "Spam Protection", level: 1, orderNo: 8, description: "Implement spam protection mechanisms at system entry and exit points." },
        { code: "SI-10", title: "Information Input Validation", level: 1, orderNo: 9, description: "Check the validity of information inputs to the information system." },
        { code: "SI-11", title: "Error Handling", level: 1, orderNo: 10, description: "Generate error messages that provide necessary information without revealing potentially harmful details." },
        { code: "SI-12", title: "Information Management and Retention", level: 1, orderNo: 11, description: "Manage and retain information within the information system in accordance with applicable requirements." },
        { code: "SI-16", title: "Memory Protection", level: 1, orderNo: 12, description: "Implement protections against unauthorized code execution in memory." },
      ],
    },
    {
      code: "PM",
      title: "Program Management",
      level: 0, orderNo: 17,
      children: [
        { code: "PM-1", title: "Information Security Program Plan", level: 1, orderNo: 1, description: "Develop and disseminate an organization-wide information security program plan." },
        { code: "PM-2", title: "Senior Information Security Officer", level: 1, orderNo: 2, description: "Appoint a senior information security officer with responsibility for the organization's security program." },
        { code: "PM-3", title: "Security and Privacy Resources", level: 1, orderNo: 3, description: "Allocate sufficient resources to implement the information security and privacy programs." },
        { code: "PM-4", title: "Plan of Action and Milestones Process", level: 1, orderNo: 4, description: "Implement a process for managing plans of action and milestones for security and privacy programs." },
        { code: "PM-5", title: "System Inventory", level: 1, orderNo: 5, description: "Develop and maintain an inventory of information systems under the organization's control." },
        { code: "PM-7", title: "Enterprise Architecture", level: 1, orderNo: 6, description: "Integrate the information security architecture into the enterprise architecture." },
        { code: "PM-8", title: "Critical Infrastructure Plan", level: 1, orderNo: 7, description: "Address information security and privacy requirements in the organization's critical infrastructure plan." },
        { code: "PM-9", title: "Risk Management Strategy", level: 1, orderNo: 8, description: "Develop and implement a comprehensive risk management strategy." },
        { code: "PM-10", title: "Authorization Process", level: 1, orderNo: 9, description: "Manage the security and privacy authorization process for information systems." },
        { code: "PM-11", title: "Mission and Business Process Definition", level: 1, orderNo: 10, description: "Define mission and business processes with consideration for security and privacy." },
      ],
    },
  ],
};
