import { CommonControl } from "../domain.layer/models/commonControl/commonControl.model";
import { CommonControlMapping } from "../domain.layer/models/commonControlMapping/commonControlMapping.model";
import { RegulationRequirement } from "../domain.layer/models/regulationRequirement/regulationRequirement.model";
import { logger } from "../utils/logger";

// 33 SCF-aligned domains covering the full GRC spectrum
const COMMON_CONTROL_DOMAINS = [
  "Access Control",
  "Asset Management",
  "Audit and Accountability",
  "Awareness and Training",
  "Business Continuity and Disaster Recovery",
  "Cloud Security",
  "Configuration Management",
  "Contingency Planning",
  "Cryptography",
  "Data Security and Privacy",
  "Development and Maintenance",
  "Emergency Management",
  "Employee Security",
  "Environmental Security",
  "Ethics and Business Conduct",
  "Financial Risk Management",
  "Governance",
  "Human Resource Security",
  "Identity and Authentication",
  "Incident Response",
  "Information Security Management",
  "Legal and Regulatory Compliance",
  "Maintenance",
  "Media Protection",
  "Monitoring and Measurement",
  "Operational Resilience",
  "Physical and Environmental Security",
  "Policy Management",
  "Procurement and Vendor Management",
  "Risk Management",
  "Security Assessment and Testing",
  "Supply Chain Risk Management",
  "System and Services Acquisition",
  "Third-Party Management",
  "Training and Awareness",
];

const SEED_COMMON_CONTROLS = [
  {
    code: "GOV-01",
    title: "Information Security Policy",
    description: "Establish, document, and maintain an information security policy approved by management.",
    objective: "Ensure management direction and support for information security aligned with business objectives.",
    domain: "Governance",
    controlWeight: "high",
    implementationGuidance: "Develop a policy that covers all security domains. Review annually. Ensure board approval.",
    assessmentCriteria: [
      "Policy exists and is approved by management",
      "Policy is reviewed at planned intervals",
      "Policy is communicated to all employees",
    ],
    evidenceRequestList: [
      "Approved information security policy document",
      "Policy review meeting minutes",
      "Policy acknowledgment records",
    ],
  },
  {
    code: "GOV-02",
    title: "Information Security Roles and Responsibilities",
    description: "Define and allocate information security responsibilities throughout the organization.",
    objective: "Ensure clear accountability for information security decisions and actions.",
    domain: "Governance",
    controlWeight: "high",
    implementationGuidance: "Define roles in job descriptions. Assign security responsibilities in the organizational chart.",
    assessmentCriteria: [
      "Roles and responsibilities are defined",
      "Accountability for security decisions is assigned",
      "Job descriptions include security responsibilities",
    ],
    evidenceRequestList: [
      "Organization chart with security roles",
      "Role descriptions",
      "Responsibility assignment matrix (RACI)",
    ],
  },
  {
    code: "GOV-03",
    title: "Management Commitment to Information Security",
    description: "Demonstrate active management commitment and sponsorship for information security across the organization.",
    objective: "Ensure management provides resources, direction, and support for information security.",
    domain: "Governance",
    controlWeight: "high",
  },
  {
    code: "GOV-04",
    title: "Integration of Security into Project Management",
    description: "Integrate information security requirements into project management methodologies and lifecycle.",
    objective: "Ensure security is considered from project initiation through delivery and operations.",
    domain: "Governance",
    controlWeight: "medium",
  },
  {
    code: "RSK-01",
    title: "Information Security Risk Assessment",
    description: "Conduct regular and ad-hoc information security risk assessments using a defined methodology.",
    objective: "Identify, analyze, and evaluate information security risks to the organization.",
    domain: "Risk Management",
    controlWeight: "high",
    implementationGuidance: "Define a risk assessment methodology. Conduct assessments at planned intervals or when significant changes occur.",
    assessmentCriteria: [
      "Risk assessment methodology is defined and approved",
      "Risk assessments are conducted at planned intervals",
      "Risk assessment results are documented and reviewed",
    ],
    evidenceRequestList: [
      "Risk assessment methodology document",
      "Completed risk assessment reports",
      "Risk register with treatment plans",
    ],
  },
  {
    code: "RSK-02",
    title: "Risk Treatment Plan",
    description: "Develop and implement a risk treatment plan to address identified information security risks.",
    objective: "Ensure identified risks are appropriately treated within defined timeframes.",
    domain: "Risk Management",
    controlWeight: "high",
  },
  {
    code: "RSK-03",
    title: "Risk Acceptance Criteria",
    description: "Define and apply criteria for accepting information security risks based on organizational risk appetite.",
    objective: "Ensure consistent risk acceptance decisions aligned with organizational risk tolerance.",
    domain: "Risk Management",
    controlWeight: "medium",
  },
  {
    code: "RSK-04",
    title: "Risk Register Maintenance",
    description: "Maintain a risk register documenting identified risks, owners, treatment plans, and status.",
    objective: "Provide a central repository for risk information to support management oversight.",
    domain: "Risk Management",
    controlWeight: "high",
  },
  {
    code: "IAC-01",
    title: "Access Control Policy",
    description: "Establish and maintain an access control policy covering logical and physical access to information assets.",
    objective: "Control access to information and information processing facilities based on business and security requirements.",
    domain: "Access Control",
    controlWeight: "high",
    implementationGuidance: "Define access control rules, rights, and restrictions. Review access regularly.",
    assessmentCriteria: [
      "Access control policy exists and is approved",
      "Access rights are reviewed at regular intervals",
      "Access control rules are documented",
    ],
    evidenceRequestList: [
      "Access control policy document",
      "Access review records",
      "User access authorization forms",
    ],
  },
  {
    code: "IAC-02",
    title: "User Access Management",
    description: "Manage user registration, provisioning, and de-provisioning across all information systems.",
    objective: "Ensure only authorized users have access to systems and data.",
    domain: "Access Control",
    controlWeight: "high",
  },
  {
    code: "IAC-03",
    title: "Privileged Access Management",
    description: "Control and monitor the allocation and use of privileged access rights.",
    objective: "Prevent and detect unauthorized use of privileged accounts.",
    domain: "Access Control",
    controlWeight: "critical",
  },
  {
    code: "IAC-04",
    title: "Access Review and Recertification",
    description: "Review and recertify user access rights at regular intervals.",
    objective: "Maintain appropriate access by detecting and removing excessive or obsolete access rights.",
    domain: "Access Control",
    controlWeight: "high",
  },
  {
    code: "IAC-05",
    title: "Segregation of Duties",
    description: "Implement segregation of duties to reduce risk of fraud and error.",
    objective: "Ensure no single person can compromise critical processes without detection.",
    domain: "Access Control",
    controlWeight: "high",
  },
  {
    code: "CRM-01",
    title: "Cryptographic Controls",
    description: "Define and implement cryptographic controls to protect information confidentiality, integrity, and authenticity.",
    objective: "Ensure appropriate use of cryptography to protect sensitive information.",
    domain: "Cryptography",
    controlWeight: "high",
    implementationGuidance: "Define a cryptographic policy covering algorithm selection, key management, and certificate lifecycle.",
    assessmentCriteria: [
      "Cryptographic policy exists and is approved",
      "Encryption is used for sensitive data at rest and in transit",
      "Key management procedures are documented and implemented",
    ],
    evidenceRequestList: [
      "Cryptographic policy document",
      "Key management procedures",
      "Certificate inventory",
    ],
  },
  {
    code: "CRM-02",
    title: "Key Management",
    description: "Manage cryptographic keys throughout their lifecycle, including generation, storage, distribution, and destruction.",
    objective: "Protect cryptographic keys from unauthorized disclosure, modification, and misuse.",
    domain: "Cryptography",
    controlWeight: "critical",
  },
  {
    code: "PHY-01",
    title: "Physical Security Perimeter",
    description: "Implement security perimeters to protect areas containing information processing facilities.",
    objective: "Prevent unauthorized physical access to information and information processing facilities.",
    domain: "Physical and Environmental Security",
    controlWeight: "medium",
    implementationGuidance: "Use physical barriers, access control systems, and security personnel to protect sensitive areas.",
    assessmentCriteria: [
      "Physical security perimeters are defined and implemented",
      "Access to sensitive areas is controlled and logged",
      "Security perimeters are tested regularly",
    ],
    evidenceRequestList: [
      "Physical security policy",
      "Access control system logs",
      "Security incident records",
    ],
  },
  {
    code: "PHY-02",
    title: "Equipment Security and Maintenance",
    description: "Protect equipment from physical and environmental threats, and maintain it properly.",
    objective: "Prevent loss, damage, theft, or compromise of equipment supporting information processing.",
    domain: "Physical and Environmental Security",
    controlWeight: "medium",
  },
  {
    code: "HR-01",
    title: "Background Screening",
    description: "Conduct background verification checks on all candidates for employment.",
    objective: "Ensure personnel are suitable for their roles and reduce risk of insider threats.",
    domain: "Employee Security",
    controlWeight: "medium",
  },
  {
    code: "HR-02",
    title: "Information Security Roles in Employment Contracts",
    description: "Include information security responsibilities in employment contracts and agreements.",
    objective: "Ensure employees understand their information security obligations.",
    domain: "Human Resource Security",
    controlWeight: "medium",
  },
  {
    code: "HR-03",
    title: "Termination and Change of Employment",
    description: "Manage the termination or change of employment responsibilities securely.",
    objective: "Protect organizational assets when employment ends or changes.",
    domain: "Human Resource Security",
    controlWeight: "high",
  },
  {
    code: "TRA-01",
    title: "Security Awareness and Training",
    description: "Provide regular security awareness training to all employees and relevant third parties.",
    objective: "Ensure personnel are aware of and fulfill their information security obligations.",
    domain: "Training and Awareness",
    controlWeight: "high",
    implementationGuidance: "Deliver annual security awareness training. Include phishing simulations. Track completion.",
    assessmentCriteria: [
      "Security awareness program exists",
      "Training completion rate exceeds 90%",
      "Phishing simulation results show improvement",
    ],
    evidenceRequestList: [
      "Training materials",
      "Training completion records",
      "Phishing simulation reports",
    ],
  },
  {
    code: "TRA-02",
    title: "Specialized Security Training",
    description: "Provide specialized information security training for personnel with specific security responsibilities.",
    objective: "Ensure personnel with security roles have appropriate skills and knowledge.",
    domain: "Training and Awareness",
    controlWeight: "medium",
  },
  {
    code: "OPS-01",
    title: "Change Management",
    description: "Implement a formal change management process for information processing facilities and systems.",
    objective: "Ensure changes are assessed, authorized, tested, and implemented in a controlled manner.",
    domain: "Configuration Management",
    controlWeight: "high",
    implementationGuidance: "Define change types (standard, normal, emergency). Require approval for all changes.",
    assessmentCriteria: [
      "Change management procedure exists and is followed",
      "Changes are approved before implementation",
      "Change records are maintained",
    ],
    evidenceRequestList: [
      "Change management policy",
      "Approved change requests",
      "Change advisory board (CAB) meeting minutes",
    ],
  },
  {
    code: "OPS-02",
    title: "Capacity Management",
    description: "Monitor and manage system capacity to ensure required performance and availability.",
    objective: "Ensure information processing capacity meets current and projected demand.",
    domain: "Operational Resilience",
    controlWeight: "medium",
  },
  {
    code: "OPS-03",
    title: "Malware Protection",
    description: "Implement malware detection, prevention, and recovery controls across all systems.",
    objective: "Protect systems and data from malware infections.",
    domain: "Information Security Management",
    controlWeight: "high",
  },
  {
    code: "OPS-04",
    title: "Backup and Recovery",
    description: "Implement and test backup and recovery procedures for all critical information and systems.",
    objective: "Ensure information can be recovered in the event of loss, corruption, or disaster.",
    domain: "Business Continuity and Disaster Recovery",
    controlWeight: "critical",
    implementationGuidance: "Define backup schedule, retention, and recovery objectives (RTO/RPO). Test restores regularly.",
    assessmentCriteria: [
      "Backup procedures are documented and implemented",
      "Backups are tested for recoverability at planned intervals",
      "Recovery time objectives (RTO) and recovery point objectives (RPO) are defined",
    ],
    evidenceRequestList: [
      "Backup policy and procedures",
      "Backup schedules and logs",
      "Restore test reports",
    ],
  },
  {
    code: "OPS-05",
    title: "Logging and Monitoring",
    description: "Implement logging and monitoring of information processing systems and security events.",
    objective: "Detect security events and support incident response and forensic investigations.",
    domain: "Monitoring and Measurement",
    controlWeight: "high",
  },
  {
    code: "OPS-06",
    title: "Vulnerability Management",
    description: "Identify, assess, and remediate technical vulnerabilities across all systems in a timely manner.",
    objective: "Prevent exploitation of known vulnerabilities.",
    domain: "Security Assessment and Testing",
    controlWeight: "high",
  },
  {
    code: "OPS-07",
    title: "Patch Management",
    description: "Apply security patches to all systems within defined timeframes based on criticality.",
    objective: "Ensure systems are protected against known vulnerabilities with available patches.",
    domain: "Configuration Management",
    controlWeight: "high",
  },
  {
    code: "OPS-08",
    title: "Network Security Management",
    description: "Manage and control network security to protect information in transit and connected systems.",
    objective: "Safeguard the confidentiality, integrity, and availability of information transmitted across networks.",
    domain: "Information Security Management",
    controlWeight: "high",
  },
  {
    code: "IAM-01",
    title: "Identity and Authentication",
    description: "Ensure all users have unique identities and are authenticated before accessing information systems.",
    objective: "Prevent unauthorized access through strong authentication mechanisms.",
    domain: "Identity and Authentication",
    controlWeight: "high",
  },
  {
    code: "IAM-02",
    title: "Multi-Factor Authentication",
    description: "Require multi-factor authentication for privileged accounts and remote access.",
    objective: "Strengthen authentication for high-risk access scenarios.",
    domain: "Identity and Authentication",
    controlWeight: "critical",
  },
  {
    code: "IAM-03",
    title: "Password Management",
    description: "Implement password policies and management controls for all systems.",
    objective: "Ensure passwords are sufficiently strong and properly managed.",
    domain: "Identity and Authentication",
    controlWeight: "high",
  },
  {
    code: "BCM-01",
    title: "Business Continuity Planning",
    description: "Develop, document, and maintain business continuity plans to address disruptive events.",
    objective: "Ensure critical business functions can continue or be recovered during and after disruptions.",
    domain: "Business Continuity and Disaster Recovery",
    controlWeight: "high",
  },
  {
    code: "BCM-02",
    title: "Disaster Recovery Planning",
    description: "Develop and maintain disaster recovery plans for critical IT systems and infrastructure.",
    objective: "Ensure timely recovery of IT systems and data following a disaster.",
    domain: "Business Continuity and Disaster Recovery",
    controlWeight: "high",
  },
  {
    code: "BCM-03",
    title: "Plan Testing and Exercises",
    description: "Test business continuity and disaster recovery plans at planned intervals.",
    objective: "Validate the effectiveness and feasibility of recovery plans.",
    domain: "Business Continuity and Disaster Recovery",
    controlWeight: "high",
  },
  {
    code: "INC-01",
    title: "Incident Management Policy",
    description: "Establish and communicate an incident management policy and procedure.",
    objective: "Ensure security incidents are consistently identified, reported, and responded to.",
    domain: "Incident Response",
    controlWeight: "high",
  },
  {
    code: "INC-02",
    title: "Incident Response Plan",
    description: "Develop and maintain an incident response plan with defined roles, procedures, and communication plans.",
    objective: "Enable effective and efficient response to security incidents.",
    domain: "Incident Response",
    controlWeight: "high",
  },
  {
    code: "INC-03",
    title: "Incident Reporting",
    description: "Establish mechanisms for personnel and external parties to report security incidents.",
    objective: "Ensure security events are reported in a timely manner for appropriate action.",
    domain: "Incident Response",
    controlWeight: "high",
  },
  {
    code: "DSP-01",
    title: "Data Classification",
    description: "Classify information according to its sensitivity, criticality, and regulatory requirements.",
    objective: "Ensure information receives appropriate protection based on its importance and sensitivity.",
    domain: "Data Security and Privacy",
    controlWeight: "high",
    implementationGuidance: "Define classification levels (e.g., public, internal, confidential, restricted). Label data accordingly.",
    assessmentCriteria: [
      "Data classification scheme exists and is approved",
      "Data is classified at creation",
      "Classification is applied consistently",
    ],
    evidenceRequestList: [
      "Data classification policy",
      "Data inventory with classification labels",
      "Training records for classification procedures",
    ],
  },
  {
    code: "DSP-02",
    title: "Data Protection and Privacy",
    description: "Implement controls to protect personal data in accordance with applicable privacy regulations.",
    objective: "Ensure compliance with data protection laws and protect individual privacy rights.",
    domain: "Data Security and Privacy",
    controlWeight: "critical",
  },
  {
    code: "DSP-03",
    title: "Data Retention and Disposal",
    description: "Define and implement data retention schedules and secure disposal procedures.",
    objective: "Ensure data is retained only as long as necessary and disposed of securely.",
    domain: "Data Security and Privacy",
    controlWeight: "medium",
  },
  {
    code: "DSP-04",
    title: "Data Transfer Controls",
    description: "Protect data during transfer across boundaries (internal and external).",
    objective: "Prevent unauthorized access to or disclosure of data in transit.",
    domain: "Data Security and Privacy",
    controlWeight: "high",
  },
  {
    code: "COM-01",
    title: "Regulatory Compliance Identification",
    description: "Identify and maintain an inventory of applicable legal, regulatory, and contractual requirements.",
    objective: "Ensure the organization is aware of and can demonstrate compliance with its obligations.",
    domain: "Legal and Regulatory Compliance",
    controlWeight: "high",
  },
  {
    code: "COM-02",
    title: "Compliance Monitoring and Reporting",
    description: "Monitor compliance with legal, regulatory, and contractual requirements on an ongoing basis.",
    objective: "Detect and address compliance gaps in a timely manner.",
    domain: "Legal and Regulatory Compliance",
    controlWeight: "high",
  },
  {
    code: "COM-03",
    title: "Intellectual Property Protection",
    description: "Implement controls to protect intellectual property rights.",
    objective: "Ensure compliance with IP laws and protect the organization's intellectual property.",
    domain: "Legal and Regulatory Compliance",
    controlWeight: "medium",
  },
  {
    code: "COM-04",
    title: "Records Management",
    description: "Manage organizational records in accordance with legal, regulatory, and business requirements.",
    objective: "Ensure records are authentic, reliable, and available when needed.",
    domain: "Legal and Regulatory Compliance",
    controlWeight: "medium",
  },
  {
    code: "TPR-01",
    title: "Third-Party Risk Assessment",
    description: "Assess the information security risks associated with third-party access, products, and services.",
    objective: "Identify and manage risks from third-party relationships before and during engagement.",
    domain: "Third-Party Management",
    controlWeight: "high",
  },
  {
    code: "TPR-02",
    title: "Third-Party Security Requirements",
    description: "Define and communicate security requirements to third parties in contracts and agreements.",
    objective: "Ensure third parties meet the organization's security expectations.",
    domain: "Third-Party Management",
    controlWeight: "high",
  },
  {
    code: "TPR-03",
    title: "Third-Party Monitoring",
    description: "Monitor third-party compliance with security requirements throughout the engagement.",
    objective: "Ensure ongoing compliance and promptly detect changes in third-party risk posture.",
    domain: "Third-Party Management",
    controlWeight: "high",
  },
  {
    code: "TPR-04",
    title: "Supply Chain Security",
    description: "Manage security risks associated with the supply chain for information and communication technology.",
    objective: "Protect against supply chain attacks and ensure product integrity.",
    domain: "Supply Chain Risk Management",
    controlWeight: "medium",
  },
  {
    code: "AUD-01",
    title: "Internal Audit Program",
    description: "Conduct internal audits of the information security management system at planned intervals.",
    objective: "Ensure the ISMS conforms to organizational requirements and is effectively implemented.",
    domain: "Audit and Accountability",
    controlWeight: "high",
  },
  {
    code: "AUD-02",
    title: "Audit Independence",
    description: "Ensure auditors are independent of the activities they audit.",
    objective: "Maintain objectivity and impartiality in audit processes.",
    domain: "Audit and Accountability",
    controlWeight: "high",
  },
  {
    code: "AUD-03",
    title: "Audit Evidence Management",
    description: "Collect, preserve, and manage audit evidence in accordance with defined procedures.",
    objective: "Ensure audit evidence is sufficient, reliable, and admissible.",
    domain: "Audit and Accountability",
    controlWeight: "medium",
  },
  {
    code: "AUD-04",
    title: "Management Review of Audit Findings",
    description: "Ensure management reviews audit findings and implements corrective actions.",
    objective: "Drive continuous improvement through audit results.",
    domain: "Audit and Accountability",
    controlWeight: "high",
  },
  {
    code: "SEC-01",
    title: "Security in Development Lifecycle",
    description: "Integrate security requirements into the system development lifecycle.",
    objective: "Ensure security is built into systems and applications from inception.",
    domain: "Development and Maintenance",
    controlWeight: "high",
  },
  {
    code: "SEC-02",
    title: "Secure Configuration Standards",
    description: "Establish and maintain secure configuration standards for all technology assets.",
    objective: "Reduce vulnerabilities through consistent secure baseline configurations.",
    domain: "Configuration Management",
    controlWeight: "high",
  },
  {
    code: "SEC-03",
    title: "Vulnerability Scanning",
    description: "Conduct regular vulnerability scans of all systems, networks, and applications.",
    objective: "Identify and prioritize vulnerabilities for remediation.",
    domain: "Security Assessment and Testing",
    controlWeight: "high",
  },
  {
    code: "SEC-04",
    title: "Penetration Testing",
    description: "Conduct periodic penetration testing of critical systems and applications.",
    objective: "Identify exploitable vulnerabilities through controlled simulated attacks.",
    domain: "Security Assessment and Testing",
    controlWeight: "high",
  },
  {
    code: "SEC-05",
    title: "Application Security Testing",
    description: "Perform security testing (SAST, DAST, SCA) as part of the software development process.",
    objective: "Identify and remediate security vulnerabilities in applications before deployment.",
    domain: "Development and Maintenance",
    controlWeight: "high",
  },
  {
    code: "ASS-01",
    title: "Asset Inventory Management",
    description: "Maintain an inventory of all information assets and assign ownership.",
    objective: "Ensure all information assets are identified, classified, and accounted for.",
    domain: "Asset Management",
    controlWeight: "high",
    implementationGuidance: "Inventory all hardware, software, and data. Update inventory on changes. Assign asset owners.",
    assessmentCriteria: [
      "Asset inventory exists and is current",
      "Asset owners are assigned",
      "Assets are classified by criticality",
    ],
    evidenceRequestList: [
      "Asset inventory register",
      "Asset classification criteria",
      "Asset disposal records",
    ],
  },
  {
    code: "ASS-02",
    title: "Acceptable Use of Assets",
    description: "Define and communicate rules for acceptable use of information assets.",
    objective: "Prevent misuse of organizational assets.",
    domain: "Asset Management",
    controlWeight: "medium",
  },
  {
    code: "ASS-03",
    title: "Asset Return and Disposal",
    description: "Ensure assets are returned and data is securely disposed of upon termination or transfer.",
    objective: "Prevent unauthorized disclosure of information from decommissioned assets.",
    domain: "Asset Management",
    controlWeight: "medium",
  },
  {
    code: "POL-01",
    title: "Policy Management Lifecycle",
    description: "Establish a process for creating, reviewing, approving, and retiring policies and standards.",
    objective: "Ensure policies are current, relevant, and effectively communicated.",
    domain: "Policy Management",
    controlWeight: "high",
  },
  {
    code: "POL-02",
    title: "Policy Acknowledgment",
    description: "Require all employees and relevant third parties to acknowledge understanding of policies.",
    objective: "Ensure personnel are aware of and commit to organizational policies.",
    domain: "Policy Management",
    controlWeight: "high",
  },
  {
    code: "CLD-01",
    title: "Cloud Security Requirements",
    description: "Define security requirements for cloud services and assess cloud provider compliance.",
    objective: "Ensure cloud services meet organizational security and compliance requirements.",
    domain: "Cloud Security",
    controlWeight: "high",
  },
  {
    code: "CLD-02",
    title: "Cloud Data Protection",
    description: "Implement controls to protect data stored and processed in cloud environments.",
    objective: "Maintain confidentiality, integrity, and availability of cloud-based data.",
    domain: "Cloud Security",
    controlWeight: "high",
  },
  {
    code: "FIN-01",
    title: "Financial Controls and Segregation",
    description: "Implement internal controls over financial reporting and segregation of financial duties.",
    objective: "Ensure accuracy and reliability of financial reporting and prevent fraud.",
    domain: "Financial Risk Management",
    controlWeight: "critical",
  },
  {
    code: "FIN-02",
    title: "Fraud Risk Management",
    description: "Establish fraud prevention, detection, and response mechanisms.",
    objective: "Minimize the risk and impact of fraudulent activities.",
    domain: "Financial Risk Management",
    controlWeight: "high",
  },
  {
    code: "EMG-01",
    title: "Emergency Preparedness and Response",
    description: "Develop and maintain emergency response procedures for various scenarios.",
    objective: "Ensure effective response to emergencies to protect life, property, and operations.",
    domain: "Emergency Management",
    controlWeight: "medium",
  },
  {
    code: "ENV-01",
    title: "Environmental Controls",
    description: "Implement environmental monitoring and controls in data centers and equipment rooms.",
    objective: "Protect equipment from environmental hazards such as fire, water, and temperature extremes.",
    domain: "Environmental Security",
    controlWeight: "medium",
  },
  {
    code: "ETH-01",
    title: "Code of Conduct and Ethics",
    description: "Establish and communicate a code of conduct covering ethical behavior and compliance.",
    objective: "Promote a culture of integrity, ethics, and compliance throughout the organization.",
    domain: "Ethics and Business Conduct",
    controlWeight: "medium",
  },

  // ── AI Governance ─────────────────────────────────────────────
  {
    code: "AI-01",
    title: "AI Governance Framework",
    description: "Establish an AI governance framework defining principles, roles, and oversight for AI system development and use.",
    objective: "Ensure responsible, transparent, and accountable AI operations aligned with organizational values.",
    domain: "Governance",
    controlWeight: "high",
    implementationGuidance: "Define AI ethics principles, assign AI oversight roles, and establish an AI review board.",
    assessmentCriteria: [
      "AI governance framework exists and is approved",
      "AI ethics principles are defined and communicated",
      "AI oversight roles and responsibilities are assigned",
    ],
    evidenceRequestList: [
      "AI governance policy",
      "AI ethics charter",
      "AI oversight committee meeting minutes",
    ],
  },
  {
    code: "AI-02",
    title: "AI Risk Assessment",
    description: "Conduct risk assessments for AI systems covering fairness, bias, transparency, and safety.",
    objective: "Identify and mitigate risks specific to AI system development and deployment.",
    domain: "Risk Management",
    controlWeight: "high",
    implementationGuidance: "Assess AI systems for bias, robustness, explainability, and societal impact before deployment.",
    assessmentCriteria: [
      "AI risk assessments are conducted before deployment",
      "Bias and fairness evaluations are performed",
      "AI risk register is maintained",
    ],
    evidenceRequestList: [
      "AI risk assessment reports",
      "Bias testing results",
      "AI risk register",
    ],
  },
  {
    code: "AI-03",
    title: "AI Model Monitoring and Validation",
    description: "Monitor AI model performance, drift, and outcomes on an ongoing basis.",
    objective: "Ensure AI models remain accurate, fair, and effective throughout their lifecycle.",
    domain: "Monitoring and Measurement",
    controlWeight: "high",
    implementationGuidance: "Implement continuous monitoring for data drift, concept drift, and model degradation.",
    assessmentCriteria: [
      "AI model monitoring is implemented",
      "Model drift detection alerts are configured",
      "Periodic model validation is performed",
    ],
    evidenceRequestList: [
      "Model monitoring dashboards",
      "Drift detection reports",
      "Model validation records",
    ],
  },
  {
    code: "AI-04",
    title: "AI Data Governance",
    description: "Govern data used for AI training, validation, and testing to ensure quality, representativeness, and compliance.",
    objective: "Prevent bias and ensure data integrity in AI systems.",
    domain: "Data Security and Privacy",
    controlWeight: "high",
    implementationGuidance: "Document data provenance, ensure training data is representative, and implement data quality checks.",
    assessmentCriteria: [
      "AI training data provenance is documented",
      "Data quality checks are performed on training data",
      "Training data is reviewed for bias",
    ],
    evidenceRequestList: [
      "Data provenance records",
      "Data quality reports",
      "Bias assessment documentation",
    ],
  },
  {
    code: "AI-05",
    title: "Human Oversight of AI Systems",
    description: "Implement human-in-the-loop or human-on-the-loop oversight for AI system decisions.",
    objective: "Ensure critical AI decisions are subject to human review and override capability.",
    domain: "Governance",
    controlWeight: "high",
    implementationGuidance: "Define which AI decisions require human review and implement override mechanisms.",
    assessmentCriteria: [
      "Human oversight mechanisms are defined and implemented",
      "Override capability exists for AI decisions",
      "Human review logs are maintained",
    ],
    evidenceRequestList: [
      "Human oversight policy",
      "AI decision review logs",
      "Override procedure documentation",
    ],
  },

  // ── Cloud Security Expansion ──────────────────────────────────
  {
    code: "CLD-03",
    title: "Cloud Service Provider Assessment",
    description: "Assess cloud service providers against security, compliance, and operational requirements before onboarding.",
    objective: "Ensure cloud providers meet organizational security and regulatory obligations.",
    domain: "Cloud Security",
    controlWeight: "high",
    implementationGuidance: "Use CSA STAR, SOC 2, or ISO 27017 certifications. Review provider shared responsibility model.",
    assessmentCriteria: [
      "Cloud providers are assessed before onboarding",
      "Provider certifications are verified",
      "Shared responsibility model is documented",
    ],
    evidenceRequestList: [
      "Cloud provider assessment reports",
      "Provider certification evidence",
      "Shared responsibility matrix",
    ],
  },
  {
    code: "CLD-04",
    title: "Cloud Security Architecture",
    description: "Design and implement a secure cloud architecture including network segmentation, encryption, and access controls.",
    objective: "Protect cloud workloads through architectural security controls.",
    domain: "Cloud Security",
    controlWeight: "high",
    implementationGuidance: "Implement cloud network segmentation, SASE/Zero Trust principles, and CSPM tools.",
    assessmentCriteria: [
      "Cloud security architecture is documented",
      "Network segmentation is implemented in cloud environments",
      "CSPM tools are deployed",
    ],
    evidenceRequestList: [
      "Cloud architecture diagrams",
      "Network segmentation configuration",
      "CSPM scanning reports",
    ],
  },
  {
    code: "CLD-05",
    title: "Cloud Workload Protection",
    description: "Protect cloud workloads including containers, serverless functions, and virtual machines.",
    objective: "Detect and prevent threats targeting cloud workloads.",
    domain: "Cloud Security",
    controlWeight: "high",
    implementationGuidance: "Deploy CWPP tools, scan container images, and implement runtime protection.",
    assessmentCriteria: [
      "Cloud workloads are protected by CWPP tools",
      "Container images are scanned for vulnerabilities",
      "Runtime protection is enabled for workloads",
    ],
    evidenceRequestList: [
      "CWPP deployment documentation",
      "Container scan reports",
      "Runtime alert records",
    ],
  },
  {
    code: "CLD-06",
    title: "Cloud Identity and Access Management",
    description: "Implement cloud IAM with least privilege, identity federation, and access analytics.",
    objective: "Ensure secure identity management across multi-cloud environments.",
    domain: "Cloud Security",
    controlWeight: "critical",
    implementationGuidance: "Use cloud IAM roles, implement federation with SSO, and monitor for anomalous access.",
    assessmentCriteria: [
      "Cloud IAM roles follow least privilege",
      "Identity federation is configured",
      "Cloud access anomalies are monitored",
    ],
    evidenceRequestList: [
      "IAM role definitions and assignments",
      "Federation configuration",
      "Cloud access anomaly reports",
    ],
  },

  // ── Business Continuity Expansion ─────────────────────────────
  {
    code: "BCM-04",
    title: "Business Impact Analysis",
    description: "Conduct business impact analysis to identify critical processes, dependencies, and recovery priorities.",
    objective: "Establish RTO/RPO for critical business functions and their supporting systems.",
    domain: "Business Continuity and Disaster Recovery",
    controlWeight: "high",
    implementationGuidance: "Identify critical processes, determine maximum tolerable downtime, and map dependencies.",
    assessmentCriteria: [
      "BIA is conducted and documented",
      "RTO and RPO are defined for critical processes",
      "Dependencies between processes are mapped",
    ],
    evidenceRequestList: [
      "BIA reports",
      "RTO/RPO register",
      "Dependency maps",
    ],
  },
  {
    code: "BCM-05",
    title: "Crisis Management",
    description: "Establish a crisis management team and procedures for managing large-scale disruptive events.",
    objective: "Ensure effective leadership and coordination during major incidents and crises.",
    domain: "Business Continuity and Disaster Recovery",
    controlWeight: "high",
    implementationGuidance: "Define crisis management team, communication plans, and crisis decision-making authority.",
    assessmentCriteria: [
      "Crisis management team is defined",
      "Crisis communication plan exists",
      "Crisis simulations are conducted",
    ],
    evidenceRequestList: [
      "Crisis management plan",
      "Communication templates",
      "Crisis simulation after-action reports",
    ],
  },
  {
    code: "BCM-06",
    title: "ICT Readiness for Business Continuity",
    description: "Ensure ICT systems and infrastructure are designed to support business continuity requirements.",
    objective: "Maintain ICT service availability and recoverability in line with business continuity objectives.",
    domain: "Business Continuity and Disaster Recovery",
    controlWeight: "high",
    implementationGuidance: "Implement redundant infrastructure, failover mechanisms, and perform ICT continuity testing.",
    assessmentCriteria: [
      "ICT continuity plans exist for critical systems",
      "Failover mechanisms are tested regularly",
      "ICT recovery capabilities meet RTO/RPO targets",
    ],
    evidenceRequestList: [
      "ICT continuity plans",
      "Failover test reports",
      "RTO/RPO achievement records",
    ],
  },

  // ── Service Management (ISO 20000) ───────────────────────────
  {
    code: "OPS-09",
    title: "Service Level Management",
    description: "Define, agree, and manage service levels for internal and external IT services.",
    objective: "Ensure IT services meet agreed quality, availability, and performance targets.",
    domain: "Operational Resilience",
    controlWeight: "high",
    implementationGuidance: "Establish SLAs, monitor service performance, and conduct regular service reviews.",
    assessmentCriteria: [
      "SLAs are defined and agreed with stakeholders",
      "Service performance is monitored against SLAs",
      "Service reviews are conducted regularly",
    ],
    evidenceRequestList: [
      "SLA documents",
      "Service performance reports",
      "Service review meeting minutes",
    ],
  },
  {
    code: "OPS-10",
    title: "Configuration Management Database",
    description: "Maintain a configuration management database of all IT assets, their relationships, and configurations.",
    objective: "Provide accurate information about IT infrastructure to support incident, problem, and change management.",
    domain: "Operational Resilience",
    controlWeight: "medium",
    implementationGuidance: "Implement a CMDB with automated discovery and maintain CI relationship mapping.",
    assessmentCriteria: [
      "CMDB is implemented and populated",
      "Configuration items are updated on changes",
      "CMDB accuracy is verified regularly",
    ],
    evidenceRequestList: [
      "CMDB reports",
      "Discovery tool configuration",
      "CMDB audit results",
    ],
  },
  {
    code: "OPS-11",
    title: "Problem Management",
    description: "Identify and manage root causes of incidents to prevent recurrence.",
    objective: "Reduce incident volume and impact through proactive problem identification and resolution.",
    domain: "Operational Resilience",
    controlWeight: "medium",
    implementationGuidance: "Establish problem management process with root cause analysis, known error database, and trend analysis.",
    assessmentCriteria: [
      "Problem management process is defined",
      "Root cause analysis is performed for major incidents",
      "Known error database is maintained",
    ],
    evidenceRequestList: [
      "Problem management procedure",
      "RCA reports",
      "Known error records",
    ],
  },

  // ── Software Security Expansion ──────────────────────────────
  {
    code: "SEC-06",
    title: "Software Supply Chain Security",
    description: "Manage security risks in the software supply chain including dependencies, third-party components, and build pipelines.",
    objective: "Prevent supply chain attacks and ensure integrity of software artifacts.",
    domain: "Development and Maintenance",
    controlWeight: "high",
    implementationGuidance: "Use SBOMs, sign software artifacts, scan dependencies, and secure CI/CD pipelines.",
    assessmentCriteria: [
      "SBOMs are generated for all software",
      "Dependencies are scanned for vulnerabilities",
      "CI/CD pipelines are hardened",
    ],
    evidenceRequestList: [
      "SBOMs for software releases",
      "Dependency scan reports",
      "CI/CD security configuration",
    ],
  },
  {
    code: "SEC-07",
    title: "API Security",
    description: "Implement security controls for APIs including authentication, authorization, rate limiting, and input validation.",
    objective: "Protect APIs from abuse, unauthorized access, and injection attacks.",
    domain: "Development and Maintenance",
    controlWeight: "high",
    implementationGuidance: "Use API gateways, enforce authentication, implement rate limiting, and perform API security testing.",
    assessmentCriteria: [
      "API security policy exists",
      "APIs are protected by authentication and authorization",
      "API security testing is performed regularly",
    ],
    evidenceRequestList: [
      "API security standards",
      "API gateway configuration",
      "API penetration test reports",
    ],
  },

  // ── Data Privacy Expansion ───────────────────────────────────
  {
    code: "DSP-05",
    title: "Consent Management",
    description: "Manage and document user consent for personal data processing activities.",
    objective: "Ensure lawful processing of personal data with valid, informed, and recorded consent.",
    domain: "Data Security and Privacy",
    controlWeight: "high",
    implementationGuidance: "Implement consent capture mechanisms, maintain consent records, and honor withdrawal of consent.",
    assessmentCriteria: [
      "Consent is obtained before data processing",
      "Consent records are maintained and auditable",
      "Consent withdrawal is honored promptly",
    ],
    evidenceRequestList: [
      "Consent management records",
      "Consent capture forms",
      "Consent withdrawal logs",
    ],
  },
  {
    code: "DSP-06",
    title: "Data Breach Notification",
    description: "Establish a data breach notification process to meet regulatory breach reporting requirements.",
    objective: "Ensure timely notification to regulators and affected individuals in case of a personal data breach.",
    domain: "Data Security and Privacy",
    controlWeight: "critical",
    implementationGuidance: "Define breach notification thresholds, timelines, and templates for regulatory reporting.",
    assessmentCriteria: [
      "Data breach notification policy exists",
      "Breach notification timelines are defined per regulation",
      "Breach notification templates are prepared",
    ],
    evidenceRequestList: [
      "Breach notification policy",
      "Regulatory notification templates",
      "Breach response exercise reports",
    ],
  },

  // ── Third-Party / Vendor Management Expansion ────────────────
  {
    code: "TPR-05",
    title: "Vendor Risk Tiering",
    description: "Classify vendors and third parties based on criticality, data access, and inherent risk.",
    objective: "Apply proportionate due diligence and monitoring based on vendor risk tier.",
    domain: "Third-Party Management",
    controlWeight: "high",
    implementationGuidance: "Define tiering criteria (data access, criticality, regulatory impact). Apply enhanced due diligence for high-risk vendors.",
    assessmentCriteria: [
      "Vendor tiering criteria are defined",
      "All vendors are assigned a risk tier",
      "High-risk vendors receive enhanced due diligence",
    ],
    evidenceRequestList: [
      "Vendor tiering policy",
      "Vendor risk tier register",
      "Enhanced due diligence reports",
    ],
  },
];

export class MetaframeworkSeeder {
  async seed(): Promise<void> {
    const existingCount = await CommonControl.count();
    if (existingCount === 0) {
      logger.info("Metaframework: Seeding common controls...");

      for (const control of SEED_COMMON_CONTROLS) {
        await CommonControl.create({
          code: control.code,
          title: control.title,
          description: control.description,
          objective: control.objective || null,
          domain: control.domain,
          controlWeight: control.controlWeight || "medium",
          implementationGuidance: control.implementationGuidance || null,
          assessmentCriteria: control.assessmentCriteria || null,
          evidenceRequestList: control.evidenceRequestList || null,
          isActive: true,
        } as any);
      }

      logger.info(`Metaframework: Seeded ${SEED_COMMON_CONTROLS.length} common controls`);
    } else {
      logger.info(`Metaframework: ${existingCount} common controls already exist, skipping seed`);
    }

    // Always run STRM mapping seeding (idempotent — uses findOrCreate)
    await this.seedMappings();
  }

  private async seedMappings(): Promise<void> {
    const commonControls = await CommonControl.findAll();
    const requirements = await RegulationRequirement.findAll({
      where: { isActive: true },
    });

    const ccMap = new Map<string, CommonControl>();
    for (const cc of commonControls) {
      ccMap.set(cc.code, cc);
    }

    let mappingCount = 0;

    // Map common controls to requirements by matching keywords:
    // GOV-01 (Security Policy) -> requirements about policy, information security policy
    // RSK-01 (Risk Assessment) -> requirements about risk assessment, risk management
    // IAC-01 (Access Control)  -> requirements about access control
    // etc.

    const keywordMappings: Array<{
      ccCode: string;
      keywordPattern: RegExp;
      relationshipType: string;
      strength: number;
    }> = [
      { ccCode: "GOV-01", keywordPattern: /information security policy/i, relationshipType: "equal_to", strength: 9 },
      { ccCode: "GOV-01", keywordPattern: /security policy/i, relationshipType: "subset_of", strength: 8 },
      { ccCode: "GOV-01", keywordPattern: /policy.*information security/i, relationshipType: "subset_of", strength: 8 },
      { ccCode: "GOV-02", keywordPattern: /roles and responsibility/i, relationshipType: "equal_to", strength: 9 },
      { ccCode: "GOV-02", keywordPattern: /security.*role/i, relationshipType: "subset_of", strength: 8 },
      { ccCode: "GOV-02", keywordPattern: /responsibility.*security/i, relationshipType: "subset_of", strength: 7 },
      { ccCode: "GOV-03", keywordPattern: /management commitment/i, relationshipType: "equal_to", strength: 9 },
      { ccCode: "GOV-03", keywordPattern: /management.*support/i, relationshipType: "subset_of", strength: 7 },
      { ccCode: "GOV-04", keywordPattern: /project management/i, relationshipType: "intersects_with", strength: 6 },
      { ccCode: "RSK-01", keywordPattern: /risk assessment/i, relationshipType: "equal_to", strength: 10 },
      { ccCode: "RSK-01", keywordPattern: /assess.*risk/i, relationshipType: "subset_of", strength: 8 },
      { ccCode: "RSK-02", keywordPattern: /risk treatment/i, relationshipType: "equal_to", strength: 9 },
      { ccCode: "RSK-03", keywordPattern: /risk acceptance/i, relationshipType: "equal_to", strength: 9 },
      { ccCode: "RSK-04", keywordPattern: /risk register/i, relationshipType: "equal_to", strength: 9 },
      { ccCode: "RSK-04", keywordPattern: /risk.*document/i, relationshipType: "subset_of", strength: 7 },
      { ccCode: "IAC-01", keywordPattern: /access control policy/i, relationshipType: "equal_to", strength: 9 },
      { ccCode: "IAC-01", keywordPattern: /access.*policy/i, relationshipType: "subset_of", strength: 8 },
      { ccCode: "IAC-02", keywordPattern: /user access.*management/i, relationshipType: "equal_to", strength: 9 },
      { ccCode: "IAC-02", keywordPattern: /user.*provision/i, relationshipType: "subset_of", strength: 8 },
      { ccCode: "IAC-02", keywordPattern: /access.*provision/i, relationshipType: "subset_of", strength: 7 },
      { ccCode: "IAC-03", keywordPattern: /privileged access/i, relationshipType: "equal_to", strength: 9 },
      { ccCode: "IAC-03", keywordPattern: /privileged.*account/i, relationshipType: "subset_of", strength: 9 },
      { ccCode: "IAC-04", keywordPattern: /access.*review/i, relationshipType: "equal_to", strength: 9 },
      { ccCode: "IAC-04", keywordPattern: /recertif/i, relationshipType: "equal_to", strength: 8 },
      { ccCode: "IAC-05", keywordPattern: /segregation.*dut/i, relationshipType: "equal_to", strength: 9 },
      { ccCode: "CRM-01", keywordPattern: /cryptograph/i, relationshipType: "equal_to", strength: 9 },
      { ccCode: "CRM-01", keywordPattern: /encryption/i, relationshipType: "subset_of", strength: 8 },
      { ccCode: "CRM-02", keywordPattern: /key management/i, relationshipType: "equal_to", strength: 9 },
      { ccCode: "PHY-01", keywordPattern: /physical.*secur/i, relationshipType: "subset_of", strength: 8 },
      { ccCode: "PHY-01", keywordPattern: /security perimeter/i, relationshipType: "equal_to", strength: 9 },
      { ccCode: "PHY-02", keywordPattern: /equipment.*secur/i, relationshipType: "equal_to", strength: 8 },
      { ccCode: "HR-01", keywordPattern: /background.*check/i, relationshipType: "equal_to", strength: 9 },
      { ccCode: "HR-01", keywordPattern: /screening/i, relationshipType: "subset_of", strength: 8 },
      { ccCode: "HR-02", keywordPattern: /employment.*terms/i, relationshipType: "intersects_with", strength: 7 },
      { ccCode: "HR-02", keywordPattern: /contract.*security/i, relationshipType: "subset_of", strength: 8 },
      { ccCode: "HR-03", keywordPattern: /termination.*employment/i, relationshipType: "equal_to", strength: 9 },
      { ccCode: "HR-03", keywordPattern: /change.*employment/i, relationshipType: "equal_to", strength: 8 },
      { ccCode: "TRA-01", keywordPattern: /security awareness/i, relationshipType: "equal_to", strength: 9 },
      { ccCode: "TRA-01", keywordPattern: /awareness.*train/i, relationshipType: "equal_to", strength: 8 },
      { ccCode: "TRA-02", keywordPattern: /specialized.*train/i, relationshipType: "equal_to", strength: 8 },
      { ccCode: "TRA-02", keywordPattern: /security.*train/i, relationshipType: "intersects_with", strength: 6 },
      { ccCode: "OPS-01", keywordPattern: /change management/i, relationshipType: "equal_to", strength: 9 },
      { ccCode: "OPS-01", keywordPattern: /change.*control/i, relationshipType: "subset_of", strength: 8 },
      { ccCode: "OPS-02", keywordPattern: /capacity management/i, relationshipType: "equal_to", strength: 9 },
      { ccCode: "OPS-03", keywordPattern: /malware/i, relationshipType: "equal_to", strength: 9 },
      { ccCode: "OPS-03", keywordPattern: /anti.?virus/i, relationshipType: "subset_of", strength: 8 },
      { ccCode: "OPS-04", keywordPattern: /backup/i, relationshipType: "equal_to", strength: 9 },
      { ccCode: "OPS-04", keywordPattern: /recovery.*data/i, relationshipType: "subset_of", strength: 8 },
      { ccCode: "OPS-05", keywordPattern: /log.*monitor/i, relationshipType: "equal_to", strength: 9 },
      { ccCode: "OPS-05", keywordPattern: /audit.*log/i, relationshipType: "subset_of", strength: 8 },
      { ccCode: "OPS-06", keywordPattern: /vulnerability management/i, relationshipType: "equal_to", strength: 9 },
      { ccCode: "OPS-07", keywordPattern: /patch management/i, relationshipType: "equal_to", strength: 9 },
      { ccCode: "OPS-08", keywordPattern: /network security/i, relationshipType: "equal_to", strength: 9 },
      { ccCode: "IAM-01", keywordPattern: /authenticat/i, relationshipType: "equal_to", strength: 8 },
      { ccCode: "IAM-01", keywordPattern: /identity/i, relationshipType: "subset_of", strength: 7 },
      { ccCode: "IAM-01", keywordPattern: /unique.*user/i, relationshipType: "subset_of", strength: 8 },
      { ccCode: "IAM-02", keywordPattern: /multi.?factor/i, relationshipType: "equal_to", strength: 9 },
      { ccCode: "IAM-03", keywordPattern: /password/i, relationshipType: "equal_to", strength: 8 },
      { ccCode: "BCM-01", keywordPattern: /business continuity/i, relationshipType: "equal_to", strength: 9 },
      { ccCode: "BCM-02", keywordPattern: /disaster recovery/i, relationshipType: "equal_to", strength: 9 },
      { ccCode: "BCM-03", keywordPattern: /test.*plan/i, relationshipType: "subset_of", strength: 7 },
      { ccCode: "BCM-03", keywordPattern: /exercise/i, relationshipType: "intersects_with", strength: 6 },
      { ccCode: "INC-01", keywordPattern: /incident.*policy/i, relationshipType: "equal_to", strength: 9 },
      { ccCode: "INC-02", keywordPattern: /incident response/i, relationshipType: "equal_to", strength: 9 },
      { ccCode: "INC-03", keywordPattern: /report.*incident/i, relationshipType: "equal_to", strength: 9 },
      { ccCode: "DSP-01", keywordPattern: /data classification/i, relationshipType: "equal_to", strength: 9 },
      { ccCode: "DSP-01", keywordPattern: /information classification/i, relationshipType: "equal_to", strength: 9 },
      { ccCode: "DSP-02", keywordPattern: /data protection/i, relationshipType: "subset_of", strength: 8 },
      { ccCode: "DSP-02", keywordPattern: /privacy/i, relationshipType: "equal_to", strength: 8 },
      { ccCode: "DSP-03", keywordPattern: /data retention/i, relationshipType: "equal_to", strength: 9 },
      { ccCode: "DSP-03", keywordPattern: /disposal/i, relationshipType: "subset_of", strength: 8 },
      { ccCode: "DSP-04", keywordPattern: /data transfer/i, relationshipType: "equal_to", strength: 8 },
      { ccCode: "COM-01", keywordPattern: /regulatory.*requirement/i, relationshipType: "equal_to", strength: 9 },
      { ccCode: "COM-01", keywordPattern: /legal.*requirement/i, relationshipType: "subset_of", strength: 8 },
      { ccCode: "COM-02", keywordPattern: /compliance.*monitor/i, relationshipType: "equal_to", strength: 9 },
      { ccCode: "COM-03", keywordPattern: /intellectual property/i, relationshipType: "equal_to", strength: 9 },
      { ccCode: "COM-04", keywordPattern: /records management/i, relationshipType: "equal_to", strength: 9 },
      { ccCode: "TPR-01", keywordPattern: /third.?party/i, relationshipType: "subset_of", strength: 7 },
      { ccCode: "TPR-01", keywordPattern: /vendor.*risk/i, relationshipType: "subset_of", strength: 8 },
      { ccCode: "TPR-02", keywordPattern: /third.?party.*requirement/i, relationshipType: "equal_to", strength: 9 },
      { ccCode: "TPR-02", keywordPattern: /contract.*security/i, relationshipType: "subset_of", strength: 7 },
      { ccCode: "TPR-03", keywordPattern: /third.?party.*monitor/i, relationshipType: "equal_to", strength: 9 },
      { ccCode: "TPR-04", keywordPattern: /supply chain/i, relationshipType: "equal_to", strength: 9 },
      { ccCode: "AUD-01", keywordPattern: /internal audit/i, relationshipType: "equal_to", strength: 9 },
      { ccCode: "AUD-02", keywordPattern: /audit.*independ/i, relationshipType: "equal_to", strength: 9 },
      { ccCode: "AUD-03", keywordPattern: /audit.*evidence/i, relationshipType: "equal_to", strength: 9 },
      { ccCode: "AUD-04", keywordPattern: /management review/i, relationshipType: "subset_of", strength: 7 },
      { ccCode: "SEC-01", keywordPattern: /security.*develop/i, relationshipType: "equal_to", strength: 9 },
      { ccCode: "SEC-01", keywordPattern: /secure.*lifecycle/i, relationshipType: "equal_to", strength: 9 },
      { ccCode: "SEC-02", keywordPattern: /secure config/i, relationshipType: "equal_to", strength: 9 },
      { ccCode: "SEC-02", keywordPattern: /baseline.*config/i, relationshipType: "subset_of", strength: 8 },
      { ccCode: "SEC-03", keywordPattern: /vulnerability.*scan/i, relationshipType: "equal_to", strength: 9 },
      { ccCode: "SEC-04", keywordPattern: /penetration test/i, relationshipType: "equal_to", strength: 9 },
      { ccCode: "SEC-05", keywordPattern: /application.*secur/i, relationshipType: "subset_of", strength: 7 },
      { ccCode: "SEC-05", keywordPattern: /sast|dast|sca/i, relationshipType: "subset_of", strength: 8 },
      { ccCode: "ASS-01", keywordPattern: /asset inventory/i, relationshipType: "equal_to", strength: 9 },
      { ccCode: "ASS-01", keywordPattern: /information asset/i, relationshipType: "subset_of", strength: 8 },
      { ccCode: "ASS-02", keywordPattern: /acceptable use/i, relationshipType: "equal_to", strength: 9 },
      { ccCode: "ASS-03", keywordPattern: /asset.*return/i, relationshipType: "equal_to", strength: 9 },
      { ccCode: "ASS-03", keywordPattern: /asset.*disposal/i, relationshipType: "equal_to", strength: 8 },
      { ccCode: "POL-01", keywordPattern: /policy.*lifecycle/i, relationshipType: "equal_to", strength: 9 },
      { ccCode: "POL-01", keywordPattern: /policy.*review/i, relationshipType: "subset_of", strength: 8 },
      { ccCode: "POL-02", keywordPattern: /acknowledge/i, relationshipType: "equal_to", strength: 8 },
      { ccCode: "CLD-01", keywordPattern: /cloud.*secur/i, relationshipType: "subset_of", strength: 7 },
      { ccCode: "CLD-02", keywordPattern: /cloud.*data/i, relationshipType: "subset_of", strength: 7 },
      { ccCode: "FIN-01", keywordPattern: /financial.*control/i, relationshipType: "equal_to", strength: 9 },
      { ccCode: "FIN-01", keywordPattern: /segregation.*dut/i, relationshipType: "intersects_with", strength: 6 },
      { ccCode: "FIN-02", keywordPattern: /fraud/i, relationshipType: "equal_to", strength: 9 },
      { ccCode: "EMG-01", keywordPattern: /emergency/i, relationshipType: "equal_to", strength: 8 },
      { ccCode: "ENV-01", keywordPattern: /environmental.*control/i, relationshipType: "equal_to", strength: 8 },
      { ccCode: "ETH-01", keywordPattern: /code of conduct/i, relationshipType: "equal_to", strength: 9 },
      { ccCode: "ETH-01", keywordPattern: /ethic/i, relationshipType: "subset_of", strength: 8 },

      // ── AI Governance patterns ────────────────────────────────
      { ccCode: "AI-01", keywordPattern: /ai.*governance|artificial intelligence.*governance|ai.*oversight|responsible.*ai/i, relationshipType: "equal_to", strength: 9 },
      { ccCode: "AI-01", keywordPattern: /ai.*framework|ai.*policy/i, relationshipType: "subset_of", strength: 8 },
      { ccCode: "AI-02", keywordPattern: /ai.*risk|artificial intelligence.*risk/i, relationshipType: "equal_to", strength: 9 },
      { ccCode: "AI-02", keywordPattern: /bias.*assessment|fairness.*assessment/i, relationshipType: "subset_of", strength: 8 },
      { ccCode: "AI-03", keywordPattern: /model.*monitor|ai.*monitor|model.*drift/i, relationshipType: "equal_to", strength: 9 },
      { ccCode: "AI-03", keywordPattern: /model.*valid/i, relationshipType: "subset_of", strength: 8 },
      { ccCode: "AI-04", keywordPattern: /ai.*data|training.*data.*governance/i, relationshipType: "equal_to", strength: 9 },
      { ccCode: "AI-04", keywordPattern: /data.*provenance.*ai/i, relationshipType: "subset_of", strength: 8 },
      { ccCode: "AI-05", keywordPattern: /human.*oversight|human.*in.*loop|human.*on.*loop/i, relationshipType: "equal_to", strength: 9 },
      { ccCode: "AI-05", keywordPattern: /ai.*review|ai.*override/i, relationshipType: "subset_of", strength: 8 },

      // ── Cloud Security expansion patterns ─────────────────────
      { ccCode: "CLD-03", keywordPattern: /cloud.*provider.*assess|cloud.*assess|provider.*certif|csa.*star/i, relationshipType: "equal_to", strength: 9 },
      { ccCode: "CLD-03", keywordPattern: /shared.*responsibility/i, relationshipType: "subset_of", strength: 8 },
      { ccCode: "CLD-04", keywordPattern: /cloud.*architecture|cloud.*network.*segment|zero.*trust.*cloud/i, relationshipType: "equal_to", strength: 9 },
      { ccCode: "CLD-04", keywordPattern: /cspm|cloud.*secur.*posture/i, relationshipType: "subset_of", strength: 8 },
      { ccCode: "CLD-05", keywordPattern: /cloud.*workload|container.*secur|cwpp/i, relationshipType: "equal_to", strength: 9 },
      { ccCode: "CLD-05", keywordPattern: /serverless.*secur|container.*image.*scan/i, relationshipType: "subset_of", strength: 8 },
      { ccCode: "CLD-06", keywordPattern: /cloud.*iam|cloud.*identity|federat.*cloud/i, relationshipType: "equal_to", strength: 9 },
      { ccCode: "CLD-06", keywordPattern: /cloud.*least.*privilege/i, relationshipType: "subset_of", strength: 8 },

      // ── Business Continuity expansion patterns ────────────────
      { ccCode: "BCM-04", keywordPattern: /business impact analysis|bia/i, relationshipType: "equal_to", strength: 9 },
      { ccCode: "BCM-04", keywordPattern: /critical.*process|rto.*rpo/i, relationshipType: "subset_of", strength: 8 },
      { ccCode: "BCM-05", keywordPattern: /crisis management|crisis.*team/i, relationshipType: "equal_to", strength: 9 },
      { ccCode: "BCM-05", keywordPattern: /crisis.*communicat/i, relationshipType: "subset_of", strength: 8 },
      { ccCode: "BCM-06", keywordPattern: /ict.*continuity|ict.*recover|ict.*readiness/i, relationshipType: "equal_to", strength: 9 },
      { ccCode: "BCM-06", keywordPattern: /failover|redundan.*ict/i, relationshipType: "subset_of", strength: 8 },

      // ── Service Management patterns ──────────────────────────
      { ccCode: "OPS-09", keywordPattern: /service level|sla|service.*agreement/i, relationshipType: "equal_to", strength: 9 },
      { ccCode: "OPS-09", keywordPattern: /service.*performance.*monitor/i, relationshipType: "subset_of", strength: 8 },
      { ccCode: "OPS-10", keywordPattern: /cmdb|configuration management database/i, relationshipType: "equal_to", strength: 9 },
      { ccCode: "OPS-10", keywordPattern: /configuration.*item|ci.*relationship/i, relationshipType: "subset_of", strength: 8 },
      { ccCode: "OPS-11", keywordPattern: /problem management/i, relationshipType: "equal_to", strength: 9 },
      { ccCode: "OPS-11", keywordPattern: /root cause analysis|rca|known error/i, relationshipType: "subset_of", strength: 8 },

      // ── Software Supply Chain / API patterns ──────────────────
      { ccCode: "SEC-06", keywordPattern: /software supply chain|sbom|supply chain.*secur/i, relationshipType: "equal_to", strength: 9 },
      { ccCode: "SEC-06", keywordPattern: /dependency.*scan|ci.*cd.*secur/i, relationshipType: "subset_of", strength: 8 },
      { ccCode: "SEC-07", keywordPattern: /api.*secur|api.*auth|api.*gateway/i, relationshipType: "equal_to", strength: 9 },
      { ccCode: "SEC-07", keywordPattern: /rate limit|api.*injection/i, relationshipType: "subset_of", strength: 8 },

      // ── Privacy expansion patterns ────────────────────────────
      { ccCode: "DSP-05", keywordPattern: /consent.*management|user.*consent|consent.*withdraw/i, relationshipType: "equal_to", strength: 9 },
      { ccCode: "DSP-05", keywordPattern: /lawful.*basis|opt.*in|opt.*out/i, relationshipType: "subset_of", strength: 8 },
      { ccCode: "DSP-06", keywordPattern: /data breach.*notif|breach.*report|personal data breach/i, relationshipType: "equal_to", strength: 9 },
      { ccCode: "DSP-06", keywordPattern: /breach.*regulator|notif.*authorit/i, relationshipType: "subset_of", strength: 8 },

      // ── Vendor Management expansion patterns ──────────────────
      { ccCode: "TPR-05", keywordPattern: /vendor.*tier|third.?party.*tier|vendor.*classif/i, relationshipType: "equal_to", strength: 9 },
      { ccCode: "TPR-05", keywordPattern: /enhanced.*due.*diligence|high.*risk.*vendor/i, relationshipType: "subset_of", strength: 8 },

      // ── Broader patterns to catch CMMC / HIPAA / FEDRAMP ─────
      { ccCode: "IAC-01", keywordPattern: /limit.*access|access.*enforce|access control policy/i, relationshipType: "subset_of", strength: 7 },
      { ccCode: "IAC-02", keywordPattern: /account management|user.*account|manage.*account/i, relationshipType: "subset_of", strength: 8 },
      { ccCode: "IAC-03", keywordPattern: /least privilege|privileged.*account|administrator.*account/i, relationshipType: "subset_of", strength: 8 },
      { ccCode: "IAC-04", keywordPattern: /access.*recertif|access.*review/i, relationshipType: "equal_to", strength: 8 },
      { ccCode: "IAC-05", keywordPattern: /separation.*dut/i, relationshipType: "equal_to", strength: 9 },
      { ccCode: "OPS-03", keywordPattern: /malicious code|virus.*defin|malicious.*protection/i, relationshipType: "subset_of", strength: 8 },
      { ccCode: "OPS-04", keywordPattern: /backup|recover/i, relationshipType: "subset_of", strength: 7 },
      { ccCode: "OPS-05", keywordPattern: /audit.*record|audit.*generat|log.*review|audit.*log/i, relationshipType: "subset_of", strength: 8 },
      { ccCode: "OPS-06", keywordPattern: /vulnerability.*scan|periodic.*scan|scan.*system|flaw.*remedi/i, relationshipType: "subset_of", strength: 8 },
      { ccCode: "OPS-07", keywordPattern: /patch|configuration.*management/i, relationshipType: "intersects_with", strength: 6 },
      { ccCode: "OPS-08", keywordPattern: /network.*control|remote.*access|wireless.*access|network.*secur/i, relationshipType: "subset_of", strength: 7 },
      { ccCode: "IAM-01", keywordPattern: /identif.*user|unique.*identif|user.*identif/i, relationshipType: "subset_of", strength: 8 },
      { ccCode: "IAM-02", keywordPattern: /multi.?factor|mfa|two.?factor/i, relationshipType: "equal_to", strength: 9 },
      { ccCode: "IAM-03", keywordPattern: /password|logon.*attempt|unsuccessful.*logon|authenticator.*manag/i, relationshipType: "subset_of", strength: 7 },
      { ccCode: "TRA-01", keywordPattern: /security.*awareness|awareness.*train|role.*train/i, relationshipType: "equal_to", strength: 8 },
      { ccCode: "INC-02", keywordPattern: /incident.*handl|incident.*capability|incident.*response.*plan/i, relationshipType: "subset_of", strength: 8 },
      { ccCode: "INC-03", keywordPattern: /escalat|report.*incident|incident.*report|incident.*track|incident.*notif/i, relationshipType: "subset_of", strength: 8 },
      { ccCode: "DSP-01", keywordPattern: /information.*classif|data.*classif/i, relationshipType: "equal_to", strength: 9 },
      { ccCode: "DSP-02", keywordPattern: /privacy|protected health|phi|patient.*health/i, relationshipType: "subset_of", strength: 8 },
      { ccCode: "DSP-03", keywordPattern: /data retention|disposal|sanitiz.*media|media.*protect/i, relationshipType: "subset_of", strength: 8 },
      { ccCode: "COM-01", keywordPattern: /regulatory|legal.*obligation|statutory/i, relationshipType: "subset_of", strength: 7 },
      { ccCode: "COM-02", keywordPattern: /continuous monitor|compliance.*monitor/i, relationshipType: "equal_to", strength: 8 },
      { ccCode: "TPR-01", keywordPattern: /business associate|third.?party|vendor/i, relationshipType: "subset_of", strength: 7 },
      { ccCode: "AUD-01", keywordPattern: /audit.*policy|audit.*accountability|audit.*procedur/i, relationshipType: "subset_of", strength: 8 },
      { ccCode: "PHY-01", keywordPattern: /physical.*protect|physical.*secur|facility.*control/i, relationshipType: "subset_of", strength: 8 },
      { ccCode: "PHY-02", keywordPattern: /media.*disposal|equipment.*secur/i, relationshipType: "subset_of", strength: 8 },
      { ccCode: "SEC-02", keywordPattern: /secure.*config|baseline.*config|config.*standard/i, relationshipType: "subset_of", strength: 8 },
      { ccCode: "SEC-03", keywordPattern: /vulnerability.*scan|penetration test|periodic.*scan/i, relationshipType: "equal_to", strength: 9 },
      { ccCode: "SEC-04", keywordPattern: /penetration.*test|intrusion.*detect/i, relationshipType: "subset_of", strength: 8 },
      { ccCode: "ASS-01", keywordPattern: /asset.*inventory|information.*asset/i, relationshipType: "equal_to", strength: 9 },
      { ccCode: "ASS-03", keywordPattern: /asset.*return|asset.*disposal/i, relationshipType: "subset_of", strength: 8 },
      { ccCode: "FIN-01", keywordPattern: /financial.*control|internal control|disclosure.*control/i, relationshipType: "subset_of", strength: 8 },
    ];

    for (const req of requirements) {
      const searchText = `${req.title} ${req.description || ""} ${req.implementationGuidance || ""}`;

      for (const mapping of keywordMappings) {
        if (mapping.keywordPattern.test(searchText)) {
          const cc = ccMap.get(mapping.ccCode);
          if (!cc) continue;

          const [, created] = await CommonControlMapping.findOrCreate({
            where: {
              commonControlId: cc.id,
              requirementId: req.id,
            },
            defaults: {
              commonControlId: cc.id,
              requirementId: req.id,
              relationshipType: mapping.relationshipType,
              strength: mapping.strength,
              rationale: `Auto-mapped: requirement text matches pattern "${mapping.keywordPattern.source}" for common control ${mapping.ccCode}`,
            },
          } as any);

          if (created) mappingCount++;
        }
      }
    }

    logger.info(`Metaframework: Created ${mappingCount} STRM mappings between common controls and regulation requirements`);
  }
}

export const metaframeworkSeeder = new MetaframeworkSeeder();
